### ISSUE TITLE
Why can't I see my custom overlays on the extension configuration screen?

### ISSUE THREAD

**Issue by marcandrews** [overlay-expert/help-desk#102]
**Describe the bug**
I cannot see my custom overlays on the extension configuration screen, only templates.

**To Reproduce**
1. Go to the Creator Dashboard
2. Click on Extension > My Extensions
3. Configure Overlay Expert by clicking on the gear

**Expected behavior**
I see my custom overlays and templates on the extension configuration screen.

**Comment by marcandrews** [comment]
To see your custom overlays on the extension configuration screen, please link your Twitch account to your Overlay Expert account.
1. Signing into Overlay Expert
2. Click on your profile image near the top-right
3. Click on **My account**
4. Under Other accounts, link your Twitch account

**Comment by Colaman14** [comment]
My overlay that i created does not pop up where all the overlays pop up and it just says create overlay when i go to where i want to select one and none of the generic ones pop and also the i created doesn't save and go to the choose an overlay section. Thanks, Rover

**Comment by lissney** [comment]
> My overlay that i created does not pop up where all the overlays pop up and it just says create overlay when i go to where i want to select one and none of the generic ones pop and also the i created doesn't save and go to the choose an overlay section. Thanks, Rover

literally same
