### ISSUE TITLE
Why can't I see my overlay over my stream?

### ISSUE THREAD

**Issue by marcandrews** [overlay-expert/help-desk#104]
If you cannot see your overlay over you stream, try the following:

1. If you have yet to install the Overlay Expert Twitch Extension, activate it, or configured by clicking on the gear and choosing an overlay, see [walkthrough videos](https://www.youtube.com/playlist?list=PL4BmDYH1JnCwT08jQDU63YHbpqPMZz2zF).
2. If you are watching from the Twitch App, mobile browser, or other platform other than PC, see [this issue](https://github.com/overlay-expert/help-desk/issues/97).
3. If you are watching from PC, and still cannot see your overlay, see [this issue](https://github.com/overlay-expert/help-desk/issues/26).

If you still have issues after attempting the above, please reach out via [Discord](https://overlay.expert/r/discord).

**Comment by pruebastaladro** [comment]
i already tried what you said, and i cant see the overlay i choose neither in this account which is for testing and on my main account, i´ve been trying for days, also when streaming, in the stream manager i hit the overlay-expert icon and it says "an error was encountered. please try again"

**Comment by marcandrews** [comment]
@pruebastaladro, please reach out via Discord for further support.

**Comment by SoyBoyIII** [comment]
My overlay appears fine on the extension config screen and when I go live, I can see it perfectly fine on my end in the stream manager but when I asked my viewers and friends if they could see it, they all said no. Why is it that only I can see it?
