### ISSUE TITLE
Insufficient Permission

### ISSUE THREAD

**Issue by M0D4K4** [overlay-expert/help-desk#105]
Hello, 
I'm attempting to set up my twitch overlay, but I keep running into the insufficient permission error whne I attempt to upload certain png files. I couldn't find anything on the topic in known issues.

**Comment by BrooksyFC** [comment]
I am also having the same issue when uploading any PNG's or JPG's

**Comment by marcandrews** [comment]
This is a folder/file permission issue. Please correct the file permission of the image you wish to upload and try again. [Search Google](https://www.google.com/search?q=chrome+insufficient+permissions) for more information.

**Comment by PristineFrog530** [comment]
So is there a solution for this issue? Just fyi it is not an issue with any settings on my files, as previously uploaded items cannot be re-uploaded. I just got a new overlay package built, and i cannot even upload it and set it up for use.
![Screenshot 2020-11-02 at 3 50 21 PM](https://user-images.githubusercontent.com/73859778/97931737-25319780-1d23-11eb-8e42-b26f7c976825.png)

**Comment by marcandrews** [comment]
I am currently working on this and will post an update to Twitter when it is resolved.

Thanks for bringing this to my attention and your patience 💜

**Comment by PristineFrog530** [comment]
Thanks, i love this extension. As a mobile streamer its only way to get reliable overlay support, it is a very useful thing for me.

**Comment by marcandrews** [comment]
@PristineFrog530 can you confirm that the issue is resolved?

**Comment by PristineFrog530** [comment]
Greetings,

Thanks for getting that fixed, can confirm it is working now. Awesome job.

Thanks,
Chris Bassett

**Comment by marcandrews** [comment]
Sweet! Thanks 💜
