### ISSUE TITLE
Im trying to use the quick chat toggle but it wont work

### ISSUE THREAD

**Issue by sliperysquid999** [overlay-expert/help-desk#107]
**Describe the bug**

I have a layer that has the quick chat toggle thing on, but whenever I use the command in chat, the layer stays on.

**To Reproduce**
1. make a new layer
2. scroll down to chat quick toggle
3. make Twitch your chat API
4. make a toggle message
5. use the overlay on stream 
6. type the command
7. see error

**Expected behavior**

the command will not work and the layer will stay on

**Twitch channel**
https://twitch.tv/sliperysquid999

**Screenshots**
[e.g. Builder, Extension Configuration Screen, etc.]

I have a test stream where I try it and it doesn't work

**Desktop (please complete the following information):**
 - OS: Chrome, or xbox, I'm on a chromebook
 - Browser: chrome
 - Version: 22

**Smartphone (please complete the following information):**
 - Device: iPhone6
 - OS: iOS12.4.8
 - Browser: safari
 - Version: 22

**Additional context**

**Comment by sliperysquid999** [comment]
im currently just manually hiding the layer I want hidden and saving, and that works

**Comment by marcandrews** [comment]
Can you sign out and sign back into Overlay Expert?

**Comment by PrimeJ** [comment]
Hi, im experiencing the same issue. Signing out and back in didnt fix it unfortunately.

**Comment by Mafiaproo** [comment]
hello me too I have this same problem, and it’s very annoying know you how to solve it

**Comment by marcandrews** [comment]
Chat toggles are working. Please confirm that you have set them up correctly by testing them in the builder before going live. If you are editing your overlay while live streaming, please wait 1 min after saving before trying your chat toggle on stream.
