### ISSUE TITLE
overlay not popping up on configuration screen

### ISSUE THREAD

**Issue by ghostyios** [overlay-expert/help-desk#108]
**Describe the bug**
when i se the overlay to overlay 1 and click the gear no extensions pop up
**To Reproduce**
1. Go to 'extentions'
2. Click on 'the gear icon on the extention'
3. Scroll down to 'nothing'

**Expected behavior**
i expected me to click configure and some overlays pop up for me to choose from

**Twitch channel**
https://twitch.tv/Ghostyios

**Screenshots**
![image](https://user-images.githubusercontent.com/73730587/97771034-0951aa00-1b07-11eb-89c3-780ad0b9b358.png)

**Desktop (please complete the following information):**
 - OS: chrome
 - Browser chrome
 - Version latest

**Smartphone (please complete the following information):**

**Additional context**

**Comment by marcandrews** [comment]
See #26
