### ISSUE TITLE
Add the URL img please

### ISSUE THREAD

**Issue by overvoidjs** [overlay-expert/help-desk#111]
I think we need a URL base add IMG. Because it can solve the DonationAlert problem with the fundraising widget on consoles. Now this problem is not solved without OBS.

**Comment by marcandrews** [comment]
Overlay Expert already supports donation alerts even without OBS. See the [announcement](https://twitter.com/OverlayExpert/status/1310269273718358017) for more information.

**Comment by overvoidjs** [comment]
> Overlay Expert already supports donation alerts even without OBS. See the [announcement](https://twitter.com/OverlayExpert/status/1310269273718358017) for more information.

Yeah Stripe it's cool but I'm from Russia and Stripe dose not support my country and our banks :(

**Comment by marcandrews** [comment]
Aw shucks, I didn't know 😞 

There is too much fraud with "other" payment platforms so only Stripe is supported, at least right now. Go to https://stripe.com/global to see which countries Stripe supports and to register to be notified when support for Russia is added.

**Comment by SmashnDash111** [comment]
My donation alert is not working

**Comment by SmashnDash111** [comment]
It had a big pink alert with a preview written after it

**Comment by marcandrews** [comment]
@SmashnDash111 Please create a new issue.
