### ISSUE TITLE
my veiwers cannot see my overlays and i have actiavted the overlays

### ISSUE THREAD

**Issue by ddddddddddhelp** [overlay-expert/help-desk#112]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Twitch channel**
https://twitch.tv/username

**Screenshots**
[e.g. Builder, Extension Configuration Screen, etc.]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by marcandrews** [comment]
See #104

**Comment by WickedRaven** [comment]
I'm noticing that you can't see the overlays on a mobile device, is this a common issue? is there a workaround? me and a few of my friends tried to look across different phones (all of them newer, software is fully up-to-date) and none of us can see the overlays on the twitch app.
