### ISSUE TITLE
Aw Snap error

### ISSUE THREAD

**Issue by nr248** [overlay-expert/help-desk#115]
I am new to the overlay expert and I used the streamelements overlay with pixlr to create a background as per a youtube video. Now In the overlay expert builder, it won't let me upload the background or any background file from my PC and shows the error in the image that I
![error image](https://user-images.githubusercontent.com/73863107/97937944-1d3b1d00-1d4e-11eb-8e36-456d346ffcb0.png)
 have attached.
Please help out

**Comment by marcandrews** [comment]
Duplicate #105
