### ISSUE TITLE
BUGS-NOT WORKING

### ISSUE THREAD

**Issue by Laura2995** [overlay-expert/help-desk#116]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Twitch channel**
https://twitch.tv/ttvdiremoonwolf

**Screenshots**
[e.g. Builder, Extension Configuration Screen, etc.]

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari]-Microsoft Edge

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] IPhone XR
 - OS: [e.g. iOS8.1] IOS 14.1
 - Browser [e.g. stock browser, safari] Safari

**Additional context**
I created an overlay for my stream (i stream on PS4), its all ready to go and to be used, but i didnt get an option to choose it or get a beta tester thing, now its not even showing in my overlays when i click on my overlays even though i have saved it even if i go back to edit something on it, i have it. could someone help me to get it working and popping up on my streams/tv for my viewers to see, also would the alerts work? i have alerts through streamlabs but not sure if they pop up in my stream/tv. i have watched videos on how to make an overlay but i only get the option to preview or edit it. can someone please help me?

**Comment by marcandrews** [comment]
All of your questions are answered [here](https://github.com/overlay-expert/help-desk/issues/1).
