### ISSUE TITLE
Stream overlay game screen size

### ISSUE THREAD

**Issue by ASpaceCow** [overlay-expert/help-desk#117]
I've been trying to sort this out for hours now but i can't. On Overlay Expert my overlay is quite big. A screenshot has been linked. 
![1604740279184](https://user-images.githubusercontent.com/74095232/98437848-ad29ef80-20dd-11eb-872c-b9abb581c214.png)
However, I would like to change the game screen size because currently it looks like this.
![Screenshot 2020-11-07 at 09 46 57](https://user-images.githubusercontent.com/74095232/98437921-3a6d4400-20de-11eb-80e9-aedc02260c0a.png)
Please help me with this problem.
Thank you for your time :)

**Comment by marcandrews** [comment]
Are you using the Twitch Extension?

**Comment by ASpaceCow** [comment]
Yes

**Comment by marcandrews** [comment]
Twitch Extensions cannot modify the source video in any way. The only way to get your source to fit your overlay is to:
1. enable Spectator Message and Comments (PS4), or;
2. use a PC, capture card and OBS.
