### ISSUE TITLE
Not fetching cheer data and last subscriptor

### ISSUE THREAD

**Issue by periflo90** [overlay-expert/help-desk#119]
**Describe the bug**
I created a layer with a Cheer Leader Month Display Name and Bits. However, it doesn't fetch the data and displays nothing than a couple of parentheses I included in the layer.

**To Reproduce**
1. Create a layer with the following content: ``Cheer Leader Month Display Name`` (``Cheer Leader Month Bits``)
2. The layer only displays () instead of John Doe (300).

**Expected behavior**
It should show this Month's Cheer Leader, who donated 300 bits. It is not an issue of time, because I got Bits yesterday and that person isn't shown either.

**Twitch channel**
https://twitch.tv/xyamagishi

**Screenshots**
![Muestra1](https://user-images.githubusercontent.com/7262313/98854657-1f426180-245b-11eb-9427-c4d3a0814517.png)
![Muestra2](https://user-images.githubusercontent.com/7262313/98854663-210c2500-245b-11eb-96a7-ec69775e6044.png)
![Muestra3](https://user-images.githubusercontent.com/7262313/98854986-9c6dd680-245b-11eb-91eb-21f9b4bf26a2.png)
![Muestra4](https://user-images.githubusercontent.com/7262313/98855045-b1e30080-245b-11eb-9ad1-dad7bb47603b.png)

**Desktop (please complete the following information):**
Windows 10.
Mozilla Firefox 82.0.3.
OBS 26.0.2

**Smartphone (please complete the following information):**
Haven't tried on phone.

**Additional context**
I added the overlay as a resource in OBS so it'll persist in the VOD.

# UPDATE 1
The last subscriptor widget stopped working. It worked for a day. Now it shows this:
![imagen](https://user-images.githubusercontent.com/7262313/98941044-45641200-24ec-11eb-9aee-ceb320cb0f63.png)
![imagen](https://user-images.githubusercontent.com/7262313/98941101-5ca2ff80-24ec-11eb-8d07-7bb11f32b6e9.png)

**Comment by marcandrews** [comment]
This issue is already tracked in #5, but I closed it in favor of this issue. I appreciate the detailed report, but in the future, please search for issues before posting.

> The last subscriptor widget stopped working.
Please sign out and sign back in with Twitch. To make tracking easier, please only include one bug per issue.

**Comment by periflo90** [comment]
I apologize. Because of the language barrier I had no idea what to search for.

> Please sign out and sign back in with Twitch. To make tracking easier, please only include one bug per issue.
Still nothing. Thank you anyway.

**Comment by marcandrews** [comment]
Did you sign out of **Overlay Expert** and sign back in with Twitch?

**Comment by periflo90** [comment]
I did, as instructed by your official account on Reddit, but still nothing.

**Comment by marcandrews** [comment]
Are you referring to cheer leader data or last subscriber data?

**Comment by periflo90** [comment]
As of now, neither works.

**Comment by marcandrews** [comment]
The issue with cheer data is known (#119). Please limit one one problem per issue and create a new issue for your subscriber data problem, or reach out via [Discord](https://overlay.expert/r/discord) for more help.
