### ISSUE TITLE
Not being able to use overlay?! 

### ISSUE THREAD

**Issue by Laura2995** [overlay-expert/help-desk#120]
![image](https://user-images.githubusercontent.com/55681375/99224928-cd783f00-27ac-11eb-9785-56153999b329.jpg)
So i made a new overlay but again it doesnt give me the option to use it. Also says i have 0 subs when i have 8. How can i use my overlay?

**Comment by Laura2995** [comment]
I got it to work :)

**Comment by marcandrews** [comment]
Sweet 🏆
