### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Nerfworker21** [overlay-expert/help-desk#125]
So on my twitch, I stream from console and have a Mac Book but not a capture card so I use overlay expert for overlays and I love it! But I need help understanding what message pattern means: file:///Users/aj/Desktop/Screen%20Shot%202020-11-26%20at%2010.02.15%20PM.png
<img width="1280" alt="Screen Shot 2020-11-26 at 10 02 15 PM" src="https://user-images.githubusercontent.com/75110907/100416781-24dfa000-3034-11eb-84a7-7933edfe788d.png">

**Comment by marcandrews** [comment]
**Message pattern** is the chat message that if _Anyone_ types in your chat, this layer will show. For example, if you set Message pattern to _Hello_, when someone types _Hello_ in your chat, this layer will show. You can also use [Regular Expression](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Cheatsheet) for more advanced pattern matching.
