### ISSUE TITLE
My overlay isnt working

### ISSUE THREAD

**Issue by Blugazz** [overlay-expert/help-desk#126]
For the last few days my overlay has not changed, I just tooth a layer off and now there is and error now that I try to edit my overlay. I made a copy but now there is even an error messages popping up. Can someone help me?

**Comment by Blugazz** [comment]
Here is my current issue. What happens next is that the overlay will not change layers while I am streaming.

![20201202_084027](https://user-images.githubusercontent.com/74968074/100880842-3c2aed00-347b-11eb-835b-934c742d9224.jpg)


I don't know if I should continue making this overlay for the third time, or just give up

**Comment by marcandrews** [comment]
When does this error pop up, when you try to save?

**Comment by Blugazz** [comment]
Being, that this is a new overlay being created this message consistently appears. Even, after I save and try to go back into the overlay I have created this message appears after the one for the tutorial. This message only appears after making my third overlay.

**Comment by marcandrews** [comment]
What's your Twitch username?

**Comment by Blugazz** [comment]
blugazz

**Comment by Blugazz** [comment]
blugazz

**Comment by marcandrews** [comment]
What happens when you sign in and open your overlay in a Chrome incognito window, and then try to modify your overlay and save?

**Comment by Blugazz** [comment]
Please, give me a second to check for you.

**Comment by Blugazz** [comment]
So I've checked and nothing happens. But, yesterday during my stream on twitch it caused a major lag.

**Comment by marcandrews** [comment]
> So I've checked and nothing happens.
What do you mean nothing happens? Does it save your overlay successfully without error?

> yesterday during my stream on twitch it caused a major lag.
Twitch Extensions cannot modify or affect the video in any way, so this issue is not related to Overlay Expert.
