### ISSUE TITLE
Allow teammates auth to one's Overlay Expert builder.

### ISSUE THREAD

**Issue by Erf-** [overlay-expert/help-desk#131]
Make it possible to add editor credentials to another Twitch user/account to edit one's overlays and select the one in-use. It would avoid security issues from sharing passwords in order to create/edit/select Overlays.

**Comment by marcandrews** [comment]
Duplicates #17

**Comment by Erf-** [comment]
> Duplicates #17

Absolutely not

**Comment by Erf-** [comment]
This is a very common pattern. It has absolutely nothing to see with sharing overlays

**Comment by Erf-** [comment]
This is not about sharing overlays, it's a very common pattern in design/creation context. A simple list of examples using this pattern :

Facebook pages roles
Twitter Deck teams
Twitch roles
...

**Comment by marcandrews** [comment]
What is planned for sharing overlays is the ability for User A to create an overlay, and then share that overlay with User B. User A will be able to modify the shared overlay and User B will be able to see the updates. User B can use the shared overlay _as-is_ and always receive updates, or use the shared overlay as a base for additional customisation.

Selecting the active overlay for another user is too much of a security risk and not currently planned. Besides this, I believe this will allow you to accomplish what you want. If not, please further clarify your use case and we will consider it.

**Comment by Erf-** [comment]
Ok I see. My suggestion is more about delegating the design of overlays to another account than sharing them. In the context you presented, it would be user A and B can update the same source.

Since Overlay Expert delegates the authentication process to the streaming platforms, user A (streamer) needs to share their password if they want to allow user B (designer/stream manager) to edit their overlays.

Then comes roles management to allow both users to authenticate themselves with their own account but still be able to update the same source. Same as in Facebook pages where the page owner can allow othen Facebook users to post or/and edit posts.

**Comment by marcandrews** [comment]
> user A and B can update the same source

Ah I understand now. This would actually be pretty cool, and definitely possible without a complicated roles management system. I will add it to the spec.

... but yeah, a complicated roles management system is not currently planned.

If you have any other thoughts or ideas, please share them.
(Please make a new issue for new ideas)

**Comment by Erf-** [comment]
Ok perfect !
