### ISSUE TITLE
[Spoiler alert] This is not about sharing overlays. Allow teammates auth to one's Overlay Expert builder

### ISSUE THREAD

**Issue by Erf-** [overlay-expert/help-desk#132]
Make it possible to add editor credentials to another Twitch user/account to edit one's overlays and select the one in-use. It would avoid security issues from sharing passwords in order to create/edit/select Overlays **for one Twitch account**.

Again, this is not about sharing overlays, it's a very common pattern in design/creation context. A simple list of examples using this pattern :
- Facebook pages roles
- Twitter Deck teams
- Twitch roles
- ...

**Comment by marcandrews** [comment]
Duplicates #131

Please use existing issues to expand and clarify.
