### ISSUE TITLE
Issue logging into my account to access Overlays

### ISSUE THREAD

**Issue by ECHOFPS** [overlay-expert/help-desk#135]
**Describe the bug**
I am on overlay experts page but I am not able to log into any accounts to work on my custom overlays
**To Reproduce**
1. Go to 'Overlay.expert'
2. Click on 'sign in/sign up'
3. Click on 'any of the account options (twitch, twitter, facebook, or gmail)'

**Expected behavior**
I expect it to log into my account, so I can customize my overlays

**Twitch channel**
https://twitch.tv/echofps10

**Screenshots**
<img width="1160" alt="Screen Shot 2021-01-07 at 11 10 13 AM" src="https://user-images.githubusercontent.com/77118037/103922332-360ed880-50d9-11eb-8f64-8ed6ec92986a.png">

[e.g. Builder, Extension Configuration Screen, etc.]

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] iOS
 - Browser [Chrome] Chrome
 - Version [e.g. 22] Version 87.0.4280.141

**Additional context**

**Comment by marcandrews** [comment]
We're currently looking into this issue.

**Comment by marcandrews** [comment]
Follow us on Twitter for updates:
https://twitter.com/OverlayExpert/status/1347238253011881987
