### ISSUE TITLE
Cheer Leader name and Bit 

### ISSUE THREAD

**Issue by reeyako** [overlay-expert/help-desk#137]
So I have been trying to set up contents on the bottom of my overlay to show recent follower, recent subscriber , recent cheer, all of them been working fine but my Cheer Leader name and Cheer Leader Bit isn’t working at all. No matter what I set as, leader of the day, week, month, all the time. Please help me, how can I fix it. I use Mac to build.Thank you

**Comment by marcandrews** [comment]
Duplicates #5
