### ISSUE TITLE
.Webm Background

### ISSUE THREAD

**Issue by iENCEE** [overlay-expert/help-desk#138]
Hello,

I'm creating alerts for my overlay and I'm trying to add a .webm file for the background of my alerts. In the description of overlay expert it says that .webm files are supported. Have I missed a step?

Please assist when possible,

Thank you
![Screenshot (263)](https://user-images.githubusercontent.com/75098760/104444794-43f3ac00-5566-11eb-934b-7e48ed93e597.png)

**Comment by marcandrews** [comment]
What's the file size?
