### ISSUE TITLE
Delete images

### ISSUE THREAD

**Issue by odinofjustice** [overlay-expert/help-desk#139]
![Screenshot_2021-01-14-18-36-18](https://user-images.githubusercontent.com/77442644/104597648-b0d38700-56c9-11eb-9835-b0d2a26a5986.png)

When trying to select an uploaded image and/or video to use as a background for my layer(s) I am given this error. I may believe that I have uploaded too many items for my tablet to handle and was wondering whether you could include an option to delete any of all uploaded items and start fresh. This hopefully would fix the problem that I am having.

**Comment by marcandrews** [comment]
Which browser is that?

**Comment by odinofjustice** [comment]
It would be the default 'Silk Browser' on my amazon tablet. I don't have access as PC of laptop.

**Comment by marcandrews** [comment]
Can you try Chrome?

**Comment by odinofjustice** [comment]
Thanks for the suggestion but unfortunately it won't work on Chrome either
![Screenshot_2021-01-16-09-47-19](https://user-images.githubusercontent.com/77442644/104786267-93451100-57e0-11eb-8184-e7b0df7d4dc2.png)

**Comment by marcandrews** [comment]
I'm making this a priority.

In the meantime, can you join our [Discord](https://overlay.expert/r/discord) so we can go through your images and remove the ones you don't need.
