### ISSUE TITLE
Problem with create SUB and RAID Alerts

### ISSUE THREAD

**Issue by lzuriel** [overlay-expert/help-desk#141]
When I try to create a SUB and Raid alerts all alerts created stop working and when I close and open again the extension I receive this error on screen:
  
  Aw, snap!
Something went wrong while trying to complete your request. If the problem persists, please contact support.

PROVIDER INVALID

I only can habilite the Follow alert to work normal.

How I can do to solve this error and work normal alerts (SUB, RAID, CHEERS and FOLLOW) together

**Comment by marcandrews** [comment]
Can you try signing out and signing back into Overlay Expert with Twitch?

**Comment by marcandrews** [comment]
Anytime :purple_heart:
