### ISSUE TITLE
recent subscriber not syncing with overlay, its showing 'none'

### ISSUE THREAD

**Issue by RandyRasta** [overlay-expert/help-desk#142]
**Describe the bug**
When i use the option to have my recent subscribers highlited on my overlay and show the most recent 5 it just comes up with 'none' when i check my dashboard on twitch it clearerly shows that i have 2. Although my recent followers works absolutely fine. I have only been affiliated a week.

**To Reproduce**
1. Add new layer
2. content
3. edit new content item
4. remove new content item text and click on recent subscribers.
5. 'None' is the text that shows

**Expected behavior**
I have two subscribers and the names of them do not show

**Twitch channel**
https://twitch.tv/randyrasta

**Screenshots**
[e.g. Builder, Extension Configuration Screen, etc.]
![image](https://user-images.githubusercontent.com/77631667/104938508-1adc7c80-59a7-11eb-9a26-c2b4a52d52e0.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: edge
 - Version N/A

**Additional context**

**Comment by marcandrews** [comment]
Can you try signing out and signing back into Overlay Expert with Twitch?

**Comment by RandyRasta** [comment]
marc, that worked perfectly, thank you very much!
