### ISSUE TITLE
Overlay expert sound alerts and event alerts not working 

### ISSUE THREAD

**Issue by ladytesla** [overlay-expert/help-desk#143]
**Describe the bug**
While streaming my alerts I have set up after I unmute they still do not show up when I get a new follow or subscription or anything I have set up. 

**To Reproduce**

**Expected behavior**

**Twitch channel**
https://twitch.tv/ladytesla6212

**Screenshots**
[e.g. Builder, Extension Configuration Screen, etc.]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by marcandrews** [comment]
Please read #1 and follow #91.
