### ISSUE TITLE
Alerts, new subscriber text and latest cheer text not working

### ISSUE THREAD

**Issue by MooshbagDRG** [overlay-expert/help-desk#144]
**Describe the bug**
Event alerts aren't playing at all, subscribers aren't being recognised in the new sub text, it just says none and latest cheer text is not showing anything at all

**To Reproduce**

**Expected behavior**
Video and sound alerts should play for new events, latest cheer should show in text and new subscribers should be listed in the text.

**Twitch channel**
https://twitch.tv/MooshbagDRG 

**Screenshots**
[e.g. Builder, Extension Configuration Screen, etc.]

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser chrome
 - Version latest

**Additional context**

**Comment by marcandrews** [comment]
Can you try signing out and signing back into Overlay Expert with Twitch?

**Comment by MooshbagDRG** [comment]
Yeah that has helped with the alerts. The latest cheer still works when it wants to however

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
