### ISSUE TITLE
Overlay Expert Overlays Appearing on Saved Twitch Streams/Broadcasts

### ISSUE THREAD

**Issue by The-Codfathers** [overlay-expert/help-desk#145]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

Yes.  I record my broadcasts through Twitch and I noticed that my overlay appears when I stream, but it doesn't appear in the twitch video editor later.  I've attached one screenshot of the stream dashboard view that has my overlay, and a screenshot of that same stream's view from Twitch's Video Producer where I noticed that the overlay isn't there. 

**Describe the solution you'd like**

The ability to have my overlay be saved and visible as well with my Twitch streams in their video producer. 

**Screenshots**
![Screen Shot 2021-01-21 at 2 17 34 AM](https://user-images.githubusercontent.com/77775601/105322739-e4615600-5b8e-11eb-9c83-d558925b4b21.png)
![Screen Shot 2021-01-21 at 2 15 06 AM](https://user-images.githubusercontent.com/77775601/105322740-e4f9ec80-5b8e-11eb-9eba-add70e700115.png)

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

I guess getting a screen recorder through my computer, but I don't own my own computer so almost everything I have to do is web-based without having to add any additional software. 

**Additional context**

**Comment by marcandrews** [comment]
Duplicates #99
