### ISSUE TITLE
Any way to make gameplay smaller?

### ISSUE THREAD

**Issue by Hijabi** [overlay-expert/help-desk#146]
Hey there, 

I am currently using Overlay Expert extension for my twitch and have everything set up. Everything is working great from chat, alerts, camera and such but the only problem that I'm having is that my gameplay is too big. My overlay covers it and so some gameplay is missing. I was trying to see if there was a way to resize my consoles game play on overlay experts. 
I have already tried resizing on my TV and on my PS4 but none of those options work. 

Is there a way for me to shrink the gameplay to fit perfectly in my overlay box on Overlay Expert?

Thank you!

**Comment by odinofjustice** [comment]
I thought that there was an option on the right hand side of the design page.
![Uploading Screenshot_2021-01-29-17-17-15-96_3aea4af51f236e4932235fdada7d1643.jpg…]()

**Comment by Hijabi** [comment]
> I thought that there was an option on the right hand side of the design page.

There is a size & positioning option which allows me to change my overlay size, but no matter what it will cover my gameplay. That's why I'm trying to figure out how to shrink my gameplay into my overlay.

**Comment by marcandrews** [comment]
See #147.
