### ISSUE TITLE
How do you get Sound Alerts to work during stream?

### ISSUE THREAD

**Issue by typikal82** [overlay-expert/help-desk#150]
I was able to get it to work onc,e and the sound alerts would play during my stream, but I do not know what I did and now they do not play anymore. My chatbot picks up that the sound has been played but it does not play audio or display the alert during the stream.

I have copied the URL into my URL widget area on Overlay Expert and I also have Streamlabs OBS open on my PC while I stream. Is there something I need to do on Streamlabs OBS also?

**Comment by marcandrews** [comment]
You will have to recreate your alerts in Overlay Expert. See #95.
