### ISSUE TITLE
Overlay Expert issues

### ISSUE THREAD

**Issue by mralbi91** [overlay-expert/help-desk#152]
https://twitch.tv/mr_albi91

Dear Support,
I have installed and activated your Overlay on my Twitch, I make PS4 direct streams (through Share function).

1. Does the overlay run both from browsers and from mobile? 
2. Does the overlay run for all the browsers? (Chrome, Safari, etc.)

On my TEST stream I asked the people what they saw and: one guy watching from the PS4 could see the overlay, one guy watching from an Android mobile could see, one watching from Apple devices (both Mac and iPhone) could NOT see.
Please let me know how to fix this, thanks.

Best regards
Alberto Frigo

**Comment by marcandrews** [comment]
Overlays show where Twitch Extensions are supported. Please see #1 for more information.
