### ISSUE TITLE
Xbox party audio being messed up on stream

### ISSUE THREAD

**Issue by cGiFury** [overlay-expert/help-desk#153]
I've been experiencing an issue where no matter what settings or volume levels I have I'm unable to hear my party on stream and it didn't start happening until I started using this software. I'm not sure if it is a problem with this extension but it is the only other thing that I can possibly think of to fix the problem, every thing else I have tried has had no effect.

twitch.tv/cgifury

**Comment by marcandrews** [comment]
Twitch Extensions **cannot** in any way modify the source video and audio.
