### ISSUE TITLE
Trying to use Twitch sound alerts with overlay expert

### ISSUE THREAD

**Issue by Starboreduk** [overlay-expert/help-desk#154]
Hello! 
Apologise now because new to all this as only just got to affiliate on twitch. I stream through PS5 and been using overlay expert while doing so, but as soon as I hit affiliate I was given the twitch extension for the browser extension Sound Alerts. This also works with my channel points etc. But seemingly i can not fathom how to activate them through the overlay expert. The tutorial is only set up for installing to OBS or if its not you have to paste the URL extension into the other obs type systems that run your overalys. Is there a way of added it to overlay expert? 

Cheers

**Comment by marcandrews** [comment]
You can create your own chat- and bits-enabled sound alerts with Overlay Expert by creating Twitch Chat event or Twitch Cheer event layer. Best of all, you keep all the bits (Sound Alerts keeps 20%). Channel Point layer event support is coming soon.

Browser sources are currently called URL widgets in Overlay Expert; with respect to browser sources and the extension, please see #100.
