### ISSUE TITLE
Overlay Expert will not allow me to add sounds

### ISSUE THREAD

**Issue by iENCEE** [overlay-expert/help-desk#156]
Hey,

I'm creating my overlay for my stream however it will not allow me to add sounds to my alert. I have previously added sounds before however it refuses to work now. I click on the button to import new sounds and nothing pops up or shows up.

is there any possible work around? thank you

**Comment by iENCEE** [comment]
Also, It will not let me save any changes after I customize my alert. I am focused on the cheer leader alert at the moment.

**Comment by marcandrews** [comment]
Are you signed in?
