### ISSUE TITLE
My Overlay is Suddently Blank (both on app and on stream)

### ISSUE THREAD

**Issue by heynael** [overlay-expert/help-desk#160]
**Describe the bug**
My Overlay suddenly stopped showing during a live stream so I went to check on the Extension page and it was completely blank.
The item and layer list on the right displays all my items and layers but they don't appear on screen. When I click on them, i have an error message showing asking me to delete my caches, which I do but it doesn't solve the issue.

**Expected behavior**
I would like my Overlay to keep showing during my stream as it features various items such as channel goals or follower display etc. 

**Twitch channel**
https://twitch.tv/heynael_gaming

**Screenshots**
![Capture d’écran 2021-02-28 à 21 29 29](https://user-images.githubusercontent.com/79810121/109432772-20e56480-7a0d-11eb-85ee-19fb956bc3d6.png)
![Capture d’écran 2021-02-28 à 21 37 07](https://user-images.githubusercontent.com/79810121/109432777-23e05500-7a0d-11eb-9f4a-56d7b3bd9719.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Google Chrome
 - Version 88.0.4324.192

**Additional context**
I don't know if that helps but I stream on Xbox One. 

Thank you so much for your help.

Best regards,
Nael

**Comment by LikeASailor** [comment]
I came here to report the same exact issue! I hope this gets resolved soon!

**Comment by marcandrews** [comment]
I am working on a fix. Stay tuned.

**Comment by LikeASailor** [comment]
Marc, thank you so much! We appreciate you!

**Comment by marcandrews** [comment]
A fix is deploying. It should take about 15 minutes.

**Comment by LikeASailor** [comment]
You are the man... Thank you so much, Marc!!!

**Comment by marcandrews** [comment]
@heynael @LikeASailor Can you confirm that your overlays are loading in the builder and the extension now?

I am deploying an another fix to saving overlays in the builder right now.

**Comment by LikeASailor** [comment]
Still nothing from my end. It shows that all of the individual elements and layers are there, but still nothing is showing up.

**Comment by LikeASailor** [comment]
Actually, I reloaded cache and I'm seeing things again, but formatting on certain elements is very off. It's missing a lot of content.

**Comment by marcandrews** [comment]
Like text is missing?

**Comment by LikeASailor** [comment]
![Screenshot (44)](https://user-images.githubusercontent.com/79811577/109436894-d0531480-79d6-11eb-8fcc-da8ed6d3c5af.png)

It shows some info, but when I try to insert content in from of the usernames or numbers (like "Followers" or "Latest Sub") it will disappear and not save when I try to save.

**Comment by marcandrews** [comment]
> @heynael @LikeASailor Can you confirm that your overlays are loading in the builder (you may have to clear cache one more time) and the extension now?
> 
> **I am deploying an another fix to saving overlays in the builder right now.**

**Comment by LikeASailor** [comment]
Thank you! Will keep you updated if it works

**Comment by marcandrews** [comment]
@LikeASailor Can you clear your browser cache, sign back in and try editing and saving your overlay?

**Comment by LikeASailor** [comment]
Sure thing

**Comment by LikeASailor** [comment]
How do I clear the cache?

**Comment by LikeASailor** [comment]
I cleared my cache, signed back in, and it still won't save my adjustments

**Comment by marcandrews** [comment]
What adjustments are you trying to make?

**Comment by LikeASailor** [comment]
I'm trying to add text before the "131", "28" and the two usernames in the top left corner. I want to label these as "Latest Follow", "Subs", etc. It seems that I cannot save text before anything that changes live (Like updating usernames of people who follow or sub, or updating follower count).

**Comment by marcandrews** [comment]
Yes I see the issue and I am working on a fix now.

**Comment by LikeASailor** [comment]
Thanks Marc!

**Comment by marcandrews** [comment]
@LikeASailor Can you try editing and saving now?

Cool overlay btw :sparkles:

**Comment by heynael** [comment]
Hi @marcandrews ! Sorry for the late reply, I didn't realize you had added comments on this. Thank you so much for taking care of the issue.
My overlay is back but just like @LikeASailor mentioned, a lot of formatting and text was missing so I just redid it and now it's working fine. :) 

Thank you for your help! Best regards

**Comment by marcandrews** [comment]
Hey @heynael, thanks for following up.

Sorry you had to remake your overlay. The problem was caused by empty text groups. If you clear your cache, it will grab the fixed overlay from the server so your original overlay should be working if you ever need it again.

If you run into any other issues, please do not hesitate to reach out :heart:

**Comment by LikeASailor** [comment]
Hey Marc,

Sorry for the late reply! Yes, I was able to get the overlay working after some reconfiguration. Thank you for all your hard work! 

Best,
Matt
