### ISSUE TITLE
My Overlay No Longer Shows Up In Stream OR On Configuration/Editing Screen

### ISSUE THREAD

**Issue by LikeASailor** [overlay-expert/help-desk#161]
**Describe the bug**
My Overlay suddenly stopped showing during a live stream so I went to check on the Extension page and it was completely blank. The item and layer list on the right displays all my items and layers but they don't appear on screen. When I click on them, i have an error message showing asking me to delete my caches, which I do but it doesn't solve the issue. Everything shows up as it should, but I even tested streaming and nothing shows up. It worked fine last night. 

**To Reproduce**

**Expected behavior**
I want my stream's overlay to show again both on my stream and on the editing screen. 

**Twitch channel**
https://twitch.tv/LikeASailor

**Screenshots**
![Screenshot (42)](https://user-images.githubusercontent.com/79811577/109434213-0e493c00-79c9-11eb-985e-0ad1b4aa6832.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version: I don't know

**Smartphone (please complete the following information):**

**Additional context**

**Comment by marcandrews** [comment]
Duplicates #160
