### ISSUE TITLE
Choose Overlay

### ISSUE THREAD

**Issue by SoundestPage163** [overlay-expert/help-desk#164]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Twitch channel**
https://twitch.tv/username
SoundestPage163
**Screenshots**
[e.g. Builder, Extension Configuration Screen, etc.]
![image](https://user-images.githubusercontent.com/80132314/110181857-20f4b400-7dc1-11eb-9d5e-33a7b063937c.png)

**Desktop (please complete the following information):**
Microsoft Edge
**Smartphone (please complete the following information):**

**Additional context**
It will not show any of the overlays I have made

**Comment by alita8606** [comment]
I had this problem. use a VPN it will make it ok

**Comment by SAVAGEstreet218** [comment]
i have the same problem

**Comment by marcandrews** [comment]
See #26
