### ISSUE TITLE
I apologize...the error code i recieved is error 503 !!!!

### ISSUE THREAD

**Issue by SOS83g** [overlay-expert/help-desk#166]
I recently changed my password on twitch. Upon doing so my overlay disappeared. I attempted to recover my saved overlay and it was gone. i sign in & out and it keeps repeating the same the same actions. i created a new overlay and saved it. I refreshed the saved overlays and it disappeared one again giving me the error code 503 not 502. Please help.

**Comment by marcandrews** [comment]
We're currently looking into this issue.

**Comment by SOS83g** [comment]
I apologize. The error code is 503.

**Comment by marcandrews** [comment]
This should be resolved now.
