### ISSUE TITLE
Overlay Expert Error code 503

### ISSUE THREAD

**Issue by TheeMeistro** [overlay-expert/help-desk#169]
**Describe the bug**
Everytime I load the site i get this error code GRAPHQL ERROR (CODE: 503): {"RESPONSE":{"ERROR":"<HTML>\R\N<HEAD><TITLE>503 SERVICE and I cant acces my overlay Ive been using forever! If its gone for good thats ver disappointing ive been loving this app so much

**To Reproduce**
1. Go to https://overlay.expert/
2. Click on anything involving overlay builder
3. Scroll down to anything

**Expected behavior**
My overlay to show up so i can use on stream and edit, as well as being able to use the  builder in general

**Twitch channel**
https://twitch.tv/theemeistro

**Screenshots**
dont have one

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome
 - Version unknown
**Smartphone (please complete the following information):**

**Additional context**

**Comment by marcandrews** [comment]
Duplicates #166
