### ISSUE TITLE
Chat Quick Toggle

### ISSUE THREAD

**Issue by Zof-Eldrazi** [overlay-expert/help-desk#171]
**Describe the bug**
When I fully implement the use of the Chat Quick Toggle for specific layers in the builder, I am unable to successfully Toggle the layer with the command in chat. I have fiddled with various settings in attempts to get this feature to work with zero success.

**To Reproduce**
1. Go to 'Overlay Expert Builder'
2. Click on 'Edit Overlay'
3. Select/Create Layer
4. Scroll down to 'Chat Quick Toggle'
5. Apply appropriate settings.
6. Save Overlay
7. Go to Twitch Creator Dashboard
8. Apply Overlay through Extention before streaming
9. Start Stream
10. Enter previously set Chat Quick Toggle Comands

**Expected behavior**
When Chat Quick Toggle is activated, entering the Chat Command during stream should Toggle the layer registered to the entered Command

**Twitch channel**
https://twitch.tv/zof_eldrazi

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Latest Version

**Additional context**
I woukd really like any information regarding this. As I've done a lot of experimenting, I believe it to be not working, however if it is working, a guide on how to properly set it up would be wonderful. It's a feature that would greatly improve my stream quality and one I would love to utilize.

**Comment by marcandrews** [comment]
Our community has posted several walkthrough videos on chat toggles here #1; have you seen them?

**Comment by Zof-Eldrazi** [comment]
I have watched the only walk through video containing relevant information regarding scene changing using the Chat Toggle feature. I followed the steps to a T and still have not had the feature work for me.
