### ISSUE TITLE
Overlay Expert Twitch chat update not working

### ISSUE THREAD

**Issue by Blaymeister** [overlay-expert/help-desk#176]
**Describe the bug**
I have been using Overlay Expert and have built a complete Overlay with your system. However, since the recent Twitch update, the chat api updating my stream of live follows and subscribers (etc...) in chat does not update.

To the extent that I have had to uninstall the overlay I have already set up because it does not work.

**To Reproduce**
1. Go to 'my channel during live stream'
2. Click on 'Follow'
3. Scroll down to 'Chat'

**Expected behavior**
I will receive a "follow" but there will be no update in chat.
**Twitch channel**
https://twitch.tv/blaymeister

**Screenshots**
[e.g. Builder, Extension Configuration Screen, etc.]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
This is happening on Android Twitch app, Xbox and Web app. Across viewers and my own stream management application on the phone.

**Comment by marcandrews** [comment]
> 3. Scroll down to 'Chat'

I don't understand, there's no scrolling in an overlay. Can you share some screenshots or screen recordings depicting the issue?

**Comment by Blaymeister** [comment]
Hi Marc,
Thanks for the response.

What I was trying to say, is that since the recent Twitch update, the overlay hasn't been autopopulating follows etc...into chat. Something has changed, while I haven't changed the overlay expert settings at all.
I believe it happened with the previous update as well. 
I tested the Own3D alert as well just to see if it was Overlay expert doing it, but it isn't happening on either. I can only surmise that it's a change in twitch that has caused it.

It's hard to send a screen recording as it's the chat update that isn't working. The animations on the overlay are working fine.

Thanks

**Comment by marcandrews** [comment]
Overlay Expert does not put anything into your chat, so you will need to use another service, such as Nightbot, for this functionality.
