### ISSUE TITLE
Not letting Me sign in to Overlay Expert

### ISSUE THREAD

**Issue by Shadows77** [overlay-expert/help-desk#177]
Overlay Expert will not allow me to sign in anymore via twitch.  Getting error message.  Have been using it for months previously.

**Comment by Shadows77** [comment]
GRAPHQL ERROR (CODE: 504): {"RESPONSE":{"ERROR":"<HTML>\R\N<HEAD><TITLE>504 GATEWAY

**Comment by HerroCityWok** [comment]
having same problem here

**Comment by marcandrews** [comment]
I'm looking into this.

**Comment by Rgarzo** [comment]
The same thing is now happening to me. It won't let me login at all.

**Comment by marcandrews** [comment]
> The same thing is now happening to me. It won't let me login at all.

@Rgarzo what's the error message?

**Comment by Rgarzo** [comment]
The error message was “aw snap, looks like were having trouble doing this, contact support if problem persists” or something along those lines. But it actually just let me in a few minutes ago. I’ve been trying to get in for the past 2 days and it wouldn't let me but it finally just did!
