### ISSUE TITLE
Overlay-Expert/ Subscriptions followers not updating. 

### ISSUE THREAD

**Issue by KmacGG** [overlay-expert/help-desk#178]
The subscription followers handle is not updating from Twitch. 

It easy to create and use and I created the layer and found it didn't update so went back and deleted it and started again and created a new layer and it's not working again. 

Is it something I am doing wrong in the process? It works perfectly with followers just not with subscibers. I look forward to your reply.

Cheers

**Comment by marcandrews** [comment]
Did you try signing out and signing back into Overlay Expert?

**Comment by KmacGG** [comment]
I did indeed and yes it rectified it so thank you very much for your help. 
Kmac
***@***.***
