### ISSUE TITLE
Cant upload overlay

### ISSUE THREAD

**Issue by Sinnethh** [overlay-expert/help-desk#179]
I get this error code upon uploading 2 of my overlays

GraphQL Error (Code: 413): {"response":{"error":"<html>\r\n<head><title>413 Request Entity Too Large</title></head>\r\n<body>\r\n<center><h1>413 Request Entity Too Large</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n","status":413},"request":{"query":"mutation imageCreateMany($files: [Upload!]!, $type: EnumImageType) {\n imageCreateMany(files: $files, type: $type) {\n ...imageFields\n }\n}\n\nfragment imageFields on Image {\n __typename\n _user\n dimensions {\n __typename\n width\n height\n }\n originalFilename\n displayName\n mimeType\n size\n _id\n updatedAt\n createdAt\n type\n}\n","variables":{"type":"panel","files":{"0":{}}}}}

**Comment by marcandrews** [comment]
The maximum file size allowed is 10 MB. See #93.
