### ISSUE TITLE
Authorization Failed

### ISSUE THREAD

**Issue by HumanityShrine** [overlay-expert/help-desk#181]
I have a problem with overlay expert, when i paste the url in OBS this error came
--
Authorization failed please confirm your stream url, refresh your broadcasting sofyware and try again
--
I tried refreshing everything and log in and log out a lot of times, if i paste another account's overlay it works, it's just all the overlays in my accounts that give the error
How can i resolve?

**Comment by marcandrews** [comment]
Interesting; I never expected this use case.

For now, if you are switching accounts, you'll need to clear the cache in your OBS browser source plugin and re-authorize with your second account.
