### ISSUE TITLE
Stripe setup issue

### ISSUE THREAD

**Issue by happy-eggrollie** [overlay-expert/help-desk#182]
**Describe the bug**
Stripe setup could not be completed because it seems to be unable to connect to Overlay Expert when trying to set up Donation Alert (or Celebration alert)

**To Reproduce**
1. Go to Event 
2. Click on Celebration Stripe
3. Scroll down to setting up a Stripe account and review the details then hit Submit button
4. See error saying "Stripe set up Incomplete" 

Also went to My Account and attempted to connect Stripe account from the Billing tab. Same error. Prompted to review the Stripe details and said set up incomplete over and over.

**Expected behavior**
A successful integration of Stripe in Overlay Expert for Celebration alert

**Twitch channel**
https://twitch.tv/happy_eggrollie

**Screenshots**
[e.g. Builder, Extension Configuration Screen, etc.]
![image](https://user-images.githubusercontent.com/82546174/114785892-4e7f3680-9d4b-11eb-9d21-9b7cafc766b9.png)

**Desktop (please complete the following information):**
 - OS: Macbook Pro (macOS Catalina)
 - Browser [e.g. chrome, safari]: Chrome

**Smartphone (please complete the following information):**
 - Version [e.g. 22] Version 89.0.4389.114 on Chrome

**Additional context**

**Comment by marcandrews** [comment]
Hi,

I looked into your account and everything seems OK. Are you still experiencing issues? It can sometimes take a minute or two for Stripe to sync with Overlay Expert, so if you are still experiencing issues, try signing out and signing back into Overlay Expert. Let me know.

Also, I read your email. Your kind words are greatly appreciated :purple_heart:
