### ISSUE TITLE
Unlocking all the time

### ISSUE THREAD

**Issue by Lukacelz** [overlay-expert/help-desk#183]
I have to unlock my overlay everytime I use it. Can i just download it? Can i buy my design? how can I stop this from happening? I use lightstream through ps4.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Twitch channel**
https://twitch.tv/username

**Screenshots**
[e.g. Builder, Extension Configuration Screen, etc.]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by marcandrews** [comment]
With other services like StreamLabs and Stream Elements, if anyone gains access to your browser source URL, they will gain access to your Twitch account too. With Overlay Expert however, we **prevent this possibility by requiring you to unlock your overlay**.

If you stream with OBS or other streaming software, we can "save" the unlock in OBS so you do not have to unlock every time. Lightstream works differently however, and with the way they have implemented their solution, the unlock is not saved. You will need to contact them and ask them to improve their service by saving cookies and local storage between sessions.

Overlay Expert is a cloud-based service. Your overlay cannot be downloaded and you already own it so you cannot buy it.

**Comment by Lukacelz** [comment]
Okay thank you so much for the answer

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
