### ISSUE TITLE
The option to "Choose" one of My Overlays isn't there?

### ISSUE THREAD

**Issue by lolzitbelikethat** [overlay-expert/help-desk#186]
![Screenshot 2021-04-21 at 23 38 51](https://user-images.githubusercontent.com/82991794/115652196-c4127600-a2fa-11eb-9d01-44886b8d004b.png)

**Comment by marcandrews** [comment]
What's your Twitch username?

What happens when you try incognito mode with Chrome extensions disabled?

**Comment by lolzitbelikethat** [comment]
My username is:  bisolar princess.
I haven’t tried that yet.
