### ISSUE TITLE
Background Videos

### ISSUE THREAD

**Issue by malum666enach** [overlay-expert/help-desk#187]
I am having issues with the background images/videos in a new nested layer. It specifically says "set an image or VIDEO as the layer background." However, I cannot upload a video? it gives me an

 Aw, snap!
Something went wrong while trying to complete your request. If the problem persists, please contact support.

_**ONLY GIF, JPEG, PNG, WEBP AND WEBM FILES ARE ACCEPTED**_

Why does it say upload an image or VIDEO when videos are not allowed??

I Also find this frustrating because I have already uploaded an MP4 once as a background. I am using it in the overlay right now. So I could upload an MP4 before but can't now. It doesn't make any sense. 

Was the feature to upload an MP4 removed recently?

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]

**Describe the solution you'd like**

**Screenshots**

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.

**Additional context**

**Comment by marcandrews** [comment]
What is the builder URL to your overlay with the MP4 background?
