### ISSUE TITLE
sub count not displaying properly

### ISSUE THREAD

**Issue by astralsoulgaming** [overlay-expert/help-desk#188]
hi i dont know why the sub count is not displaying correctly. my twitch is linked directly to overlay expert and i have 92 but overlay expert says 0. please help also doesnt show my recent subscribers? 
![image](https://user-images.githubusercontent.com/83183366/116005868-b7717480-a5bd-11eb-919b-2d885353f9f4.png)
![image](https://user-images.githubusercontent.com/83183366/116005878-ceb06200-a5bd-11eb-8e0d-12a1d0951b1e.png)

**Comment by marcandrews** [comment]
Please sign out and sign back into Overlay Expert.
