### ISSUE TITLE
The overlay can't be see it in smartphones

### ISSUE THREAD

**Issue by cvillareal1993** [overlay-expert/help-desk#190]
**Describe the bug**
Hi my question is about the Overlay expert extension for twitch, my question is this overlay windows doesn't work in smartphones?
Because I'm staring with the stream world, and I saw this option because I'm a console streamer but in the moment that I activate the overlay in my stream the overlay can't be see it in the smartphone app of twitch is there something wrong that I'm doing wrong or there's another step to broadcast my overlays in the movil app?

**To Reproduce**

**Expected behavior**
I created an overlay template for my stream but this can't be see it in the twitch movil app

**Twitch channel**
https://twitch.tv/warzoneplay_cr

**Screenshots**
[e.g. Builder, Extension Configuration Screen, etc.]

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version [90.0.4430.93 (Build oficial) (64 bits)
 
**Smartphone (please complete the following information):**
 - Device:  Huawei Y7
 - Browser Chrome
 - Version 90.0.4430.91

**Additional context**

**Comment by marcandrews** [comment]
See #97 

Please search before creating new issues.
