### ISSUE TITLE
Alert Issue

### ISSUE THREAD

**Issue by ThinkLink86** [overlay-expert/help-desk#191]
**Describe the bug**
I'm trying to set up my Twitch Alerts. I noticed that they did not work properly last time I streamed when I got a new sub. I had a animation set to an image with the users name. This evening I tried to make a new layer with the same .PNG image. The preview animation just flickers. I've tried a few different animations and they do the same thing. I also tried another layer with just text and it's the same.

**To Reproduce**
1. New Layer  
2. Background, since I was adding an image. 
3. Alerts > Event Based > Twitch Follow 
4. Animation > Pick one > Preview, image just flickers.

**Expected behavior**
The image/text should animate. 

**Twitch channel**
https://twitch.tv/ThinkLink

**Screenshots**
[e.g. Builder, Extension Configuration Screen, etc.]

**Desktop (please complete the following information):**
 - Browser Chrome
 - Version 90.0.4430.212

**Smartphone (please complete the following information):**
Was not using my phone for this.

**Additional context**
Thank you!

**Comment by ThinkLink86** [comment]
How was the template not used properly/not enough info was provided?
You can't use overlay expert on mobile so I can't provided anything on that.
How can I screenshot the animation when it doesn't work/is the issue?
I've followed the steps provided by a few YT videos. Still doesn't work.

**Comment by marcandrews** [comment]
Thanks for using the template.

What are the specs of your PC? Which animations did you try? Can you try to open your overlay in the builder on your phone and see if the animations show there?

**Comment by ThinkLink86** [comment]
64-bit operating system. 16GB RAM. Processor: Intel(R) Core i3-8130U CPU @ 2.20GHz 2.21 GHz.
I just tried, Puff In/Out, Swash In/Out, Foolish In/Out, Tin Right In/Out. Currently still flickers onscreen. 
Tried to open overlay expert via my phone and it says "something went wrong while trying to complete your request. If the problem persists, please contact support." 
Thank you.

**Comment by marcandrews** [comment]
Can you post a screenshot of the error?

**Comment by ThinkLink86** [comment]
![Capture](https://user-images.githubusercontent.com/84162812/118430480-27958680-b6a2-11eb-836d-f5beadeb0e0f.JPG)


As stated above the image flickers onscreen (appears then disappears) when you select preview animation.

**Comment by marcandrews** [comment]
I tested your overlay and it seems to be working fine.

https://user-images.githubusercontent.com/3518829/118477538-c8a13300-b6dc-11eb-958e-10371e4e855b.mp4

Can you send a screenshot of the error you get on your phone?
