### ISSUE TITLE
Overlay Marketplace

### ISSUE THREAD

**Issue by SoundestPage163** [overlay-expert/help-desk#192]
![image](https://user-images.githubusercontent.com/80132314/119397010-7470f280-bc8a-11eb-872b-f5564f237b5c.png)

The marketplace will not appear, I have had it before in the past but this is a reoccurring issue for me where I may have the marketplace for a few weeks but most of the time I do not have it.

https://www.twitch.tv/soundestpage163

**Comment by marcandrews** [comment]
See issue #26.
