### ISSUE TITLE
music at follower

### ISSUE THREAD

**Issue by mgdamage** [overlay-expert/help-desk#196]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Twitch channel**
https://twitch.tv/username

**Screenshots**
[e.g. Builder, Extension Configuration Screen, etc.]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
 
i wanted to set a song of 3 sec on if someone followed me but if i select the song i want i get a message that i need to tell it here

**Comment by marcandrews** [comment]
What is the file type and size of the song?
