### ISSUE TITLE
Change a handle

### ISSUE THREAD

**Issue by Leok88** [overlay-expert/help-desk#201]
<!--
I connected a twitter account so that I could make a handle, but the wrong account was connected (as I have multiple twitter accounts). I can't find a way to connect my twitch to another twitter account. 

**Describe the bug**
Can't connect another different account for a handle

**To Reproduce**
1. Go to 'twitter handle'
2. Click on 'on connect twitter account'
3. Sign in with twitter
4.  Can't change the twitter account connected

**Expected behavior**
I thought I would be able to disconnect the current connected twitter account and connect a different account

**Twitch channel**
https://twitch.tv/leoooo_pog

**Screenshots**
[e.g. Builder, Extension Configuration Screen, etc.]

**Desktop (please complete the following information):**
 - OS: [unsure]
 - Browser [chrome]
 - Version [unsure]

**Smartphone (please complete the following information):**
 - Device: [iphone 12 pro max]
 - Browser [safari]
 - Version [unsure]

**Additional context**

**Comment by marcandrews** [comment]
Duplicates #80
