### ISSUE TITLE
Duplicated sound on Twitch alerts with uploaded MP3 sounds

### ISSUE THREAD

**Issue by volg3n** [overlay-expert/help-desk#207]
**Describe the bug**
The system plays duplicated the uploaded MP3 sound alerts with variable delays on each Twitch events. Broadcasting software is OBS 27.0.1

**To Reproduce**
Upload any MP3 file to the site, select it for a Twitch alert such as follower alert and test it with the Twitch chat command. Most of the times the sound duplicated and like there would be some echo. Very annoying.

**Expected behavior**
Twitch alerts should play once the uploaded and selected MP3 sound.

**Twitch channel**
https://twitch.tv/volg3n

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 93

**Additional context**
Thanks for this great free overlay plugin for Twitch. I appreciate the effort!

**Comment by marcandrews** [comment]
I just tested this an the alert sound only played once.

Usually when this happens, it means you are running/listening to your overlay while you are streaming and the alert sounds are coming through the stream with your voice.

I appreciate the feedback :purple_heart:

**Comment by volg3n** [comment]
Hi Marc, I am still experiencing the problem. Maybe it is related to MP3 bitrate? I use 192 kbit/s files is there any restrictions? I checked OBS this is the only source which gives any kind of sound in the scene (tested with the website edit section only and I got the same result). The strange thing is that couple times it fires only once per event as should normally, but the majority (90%) is doubled with echo, and the delay is different as well.

**Comment by marcandrews** [comment]
Can you join our Discord https://discord.gg/xm4S37m so we can screenshare/debug?

**Comment by volg3n** [comment]
Sorry Marc I don't have discord yet. I have done some experiment with the bitrate, so what I experienced:
- I lowered the MP3 bitrate to 96 from 192.
- If I loaded the overlay (starting OBS or load the edit page in overlay.expert site) the first event triggered the MP3 duplicated (same thing if you are selecting a newly uploaded file in overlay.expert edit page, the first time you are trying to play it with the play button next to it triggers double the play, second time it doesn't, the volume percentage setting is broken there btw :( )
- The second and the other after that sounded okay
- With higher bitrate the double trigger caused by the event is more frequent I can say randomized and the majority sounded doubled with echo.

**Comment by volg3n** [comment]
I think I am reverting back the previous comment it is still echoing randomly :(

**Comment by marcandrews** [comment]
1. What are the filenames of the MP3 files with different bitrates that you uploaded to Overlay Expert?
2. How are you triggering the event, via Stream Preview, the chat test commands, a real event, or other?

**Comment by volg3n** [comment]
1.
**96 kbit/s**
96_Destination_Unknown.mp3
96_Meet_me_at_the_club.mp3
**128 kbit/s**
128_Destination_Unknown.mp3
128_Meet_me_at_the_club.mp3
**Original 192 kbit/s**
Destination_Unknown.mp3
Meet_me_at_the_club.mp3

2.
I am triggering the event from stream manager site of Twitch from chat with the commands from here:
[](https://github.com/overlay-expert/help-desk/issues/91)
