### ISSUE TITLE
Save bug for "Rocket Rumble" overlat

### ISSUE THREAD

**Issue by jimoflame** [overlay-expert/help-desk#208]
**Describe the bug**
I get an error when I try to save my customized "Rocket Rumble" overlay.  All the other preset overlays seem to save and work fine but I play rocket league and wanted to use the rocket rumble overlay.  I get an error saying "Aw, snap!  Something went wrong while trying to complete your request."

**To Reproduce**
1. Go to 'File'
2. Click on 'Save'
4. See error "Aw, snap! Something went wrong while trying to complete your request."

**Expected behavior**
I expected it to save the overlay

**Twitch channel**
https://twitch.tv/jimoflame

**Desktop (please complete the following information):**
 - Windows 10
 - Browser Chrome
 - Version 92.0.4515.131

**Comment by marcandrews** [comment]
Are you signed in?

**Comment by jimoflame** [comment]
> Are you signed in?

Yes, other preset overlays I customize and it saves fine.  It is only the "Rocket Rumble" overlay I customize and try to save it where I get that error.
