### ISSUE TITLE
Cannot save RL Overlay changes

### ISSUE THREAD

**Issue by Jack-Newman21** [overlay-expert/help-desk#219]
-->
Problem: 
Whenever I edit the Rocket league template I am unable to save my changes, I am only having trouble when editing this template. I can edit and save others.

**To Reproduce**
1. Go to 'Rocket Rumble Template'
2. Click on 'Save'
3. Error message appears that says 'Aw, snap!
Something went wrong while trying to complete your request. If the problem persists, please contact support.'

**Expected behavior**
I expected to be able to save my changes to the overlay template

**Twitch channel**
https://www.twitch.tv/jackiemoon1025

**Screenshots**
[e.g. Builder, Extension Configuration Screen, etc.]

**Desktop (please complete the following information):**
 - MacBook Pro
 - Chrome

**Comment by marcandrews** [comment]
Yes, looks like there's an issue with that template. I will look into it further tomorrow. It should be an easy fix.

**Comment by Jack-Newman21** [comment]
Great! Thanks Marc!

**Comment by marcandrews** [comment]
I found the issue. Can you select the **Center** layer and set values for
1. Font Size 
2. Position from layer edges Top
3. Position from layer edges Right

For example ...
![Screenshot from 2021-11-13 09-17-58](https://user-images.githubusercontent.com/3518829/141647250-c85b1b48-5c40-4d89-8238-7d7e70f042ca.png)

This should allow you to save.

I also fixed the template, so you should be able to save new overlays started from this template.

Let me know how it goes.
