### ISSUE TITLE
CANT SEE MY OVERLAYS 

### ISSUE THREAD

**Issue by nazareththegod** [overlay-expert/help-desk#220]
I CREATED MY OVERLAYS AND SAVED THEM THEN WENT TO TWITCH AND ACTIVATED OVERLAYS. I PRESSED THE WHEELE AND NONE OF MY OVERLAYS ARE SHOWING IT JUST KEEPS SAYING CREATE A NEW OVERLAY

**Comment by marcandrews** [comment]
See #26.

Please search before posting an issue.
