### ISSUE TITLE
Chat Toggle commands not working

### ISSUE THREAD

**Issue by WolffyGB** [overlay-expert/help-desk#223]
When I attempt to quick toggle my overlays I am met with "unrecognised command" in my chat box.

**To Reproduce**
1. Turn Quick chat toggle on (to twitch)
2. Set command 
3. Attempt command in twitch chat box

**Expected behavior**
I expect it to either open or close (toggle on/off) my overlay(s).

**Twitch channel**
https://www.twitch.tv/wolffygb

**Screenshots**

![Screenshot (3)](https://user-images.githubusercontent.com/95227650/143876679-630ab2be-16fc-41a2-8535-75a27fc8a59e.png)

![Screenshot (2)](https://user-images.githubusercontent.com/95227650/143876695-716702a1-9273-42a4-82db-e89496ba6e90.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 96

**Comment by marcandrews** [comment]
I noticed this recently too. 

Twitch is only allowing recognised commands in chat so you will need to use `!` (exclamation mark) or something else other than `/` (forward slash) for your chat commands.
