### ISSUE TITLE
why are none of the templates OR my saved overlays visable?

### ISSUE THREAD

**Issue by sedluc1234** [overlay-expert/help-desk#233]
I've done everything that ive found to solve the issue and nothing. i've uninstalled and reinstalled, unconfigured and reconfigured, logged in and logged out. NOTHING!

i can make my overlays just fine and when i go into the my overlays tab they are there.
![Screenshot_3](https://user-images.githubusercontent.com/96840449/147692112-ec62fb38-6b29-4c56-9552-14df567b68d3.png)
![Screenshot_4](https://user-images.githubusercontent.com/96840449/147692113-4137a418-709f-4be7-baeb-a1352cb78b54.png)

when im creating one & i go to add images all of the OE template images are there.

when i actually go to select and apply my overlay this is the screen i get
![Screenshot_5](https://user-images.githubusercontent.com/96840449/147692102-a8399b40-a289-41b3-a7f9-d703879408dc.png)

i dont understand it! :(

**Comment by marcandrews** [comment]
Duplicates https://github.com/overlay-expert/help-desk/issues/26#issuecomment-642380393

**Comment by sedluc1234** [comment]
> Duplicates [#26 (comment)](https://github.com/overlay-expert/help-desk/issues/26#issuecomment-642380393)

that didn't actually help at all 🙃🙄 but thanks I guess
