### ISSUE TITLE
Bro the Extension Configuration thing doesn't show up. (I think it got lost in the shadow realm)

### ISSUE THREAD

**Issue by ShadiestMoon7** [overlay-expert/help-desk#234]
My overlays I've made doesn't show up on the extension configuration neither does the market itself. I tried to delete cookies from both the overlay expert and twitch to try to fix this but none of these didn't work. idk if I'm small brain or if the problem is too easy to solve but I need help my bruh. :(

(Pic for context)
![Screenshot (2)](https://user-images.githubusercontent.com/96898555/147802096-f4369e32-4655-46bc-99be-7c3b86f18d38.png)

**Comment by marcandrews** [comment]
Duplicates #26
