### ISSUE TITLE
Chat toggle doesn't work for me...

### ISSUE THREAD

**Issue by Notsosweatywraith** [overlay-expert/help-desk#238]
**Describe the bug**
I have an overlay that should show up on my twitch stream when i put the command in the chat and it doesn't work

**To Reproduce**
1. Go to twitch chat
2. Type command to put on "be right back" screen
3. Nothing happens

**Expected behavior**
The overlay to appear when i typed into the chat my command for that overlay to appear. The chat doesn't recognize it as a command so nothing happens

https://twitch.tv/Notsosweatywraith

**Desktop (please complete the following information):**
 - OS: Chrome OS
 - Browser chrome
 - Version 93.0.4577.107 

**Additional context**

**Comment by marcandrews** [comment]
Duplicates #223 

Please search before creating new issues.
