### ISSUE TITLE
Twitch chat widget does not show messages in builder

### ISSUE THREAD

**Issue by marcandrews** [overlay-expert/help-desk#24]
**Describe the bug**
Twitch chat widget does not show messages in builder

**To Reproduce**
1. Create a new overlay
2. Add layer and set content to Twitch Chat
3. See no test messages or real chat messages in layer

**Expected behavior**
Test messages and real chat message should show in layer

**Comment by marcandrews** [comment]
Please note that this bug is exclusive to the builder; it works when streaming with the extension.

For a workaround in the builder, please include a Twitch dynamic item, such as a Twitch Timer, in your overlay.

**Comment by Rioo94** [comment]
I have the same problem with my overlay expert. The twitch chat widget does not show messages in the builder, even when streaming.

**Comment by LielDono** [comment]
I have a similar problem where it works (Shows chat messages) in the builder but does not show on the actual stream
