### ISSUE TITLE
Alert Box

### ISSUE THREAD

**Issue by chipotleismyIyfe** [overlay-expert/help-desk#242]
Hey, I am currently trying to make my own overlay with some of the things I purchased. I was attempting to set up the follow alert box but I can't seem to find out how to stop it from cycling through all of the recent follows. I just want to see the most recent follower and have their name sitting there still. Ive tried multiple things and I cannot figure it out for the life of me.

**Comment by marcandrews** [comment]
See this tweet https://twitter.com/OverlayExpert/status/1285351921864368133.
