### ISSUE TITLE
The Subscribers says 0 and has for about a week

### ISSUE THREAD

**Issue by Chrispvlogs** [overlay-expert/help-desk#243]
<!  The subscribers says 0 even though i have subscribers and under the recent subscribers it says NONE and i do  not know how to fix. i have tried everything.

**Describe the bug**
 The subscribers says 0 even though i have subscribers and under the recent subscribers it says NONE and i do  not know how to fix. i have tried everything.

**To Reproduce**

**Expected behavior**

**Twitch channel**
https://twitch.tv/Chrispvlogs

**Screenshots**
[e.g. Builder, Extension Configuration Screen, etc.]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by marcandrews** [comment]
After signing out and signing back into Overlay Expert with Twitch, this should be resolved.

**Comment by Chrispvlogs** [comment]
Nope not fixed it still does it
