### ISSUE TITLE
Recent Subscribers content not working

### ISSUE THREAD

**Issue by RapBlueSteel** [overlay-expert/help-desk#244]
Recent Subscribers content not working

**Describe the bug**
I am having issues with the Recent Subscribers content not showing up on stream. It only says "None" on stream and does not display the most recent subscriber on the overlay editor.

**To Reproduce**
N/A. Added Recent Subscriber as a content item to a new layer but it won't display on stream.

**Expected behavior**
Should show my most recent subscriber on twitch

**Twitch channel**
https://twitch.tv/rapbluesteel

**Screenshots**
Different name showing on editor and only "None" while streaming.

**Desktop (please complete the following information):**
 - Win10
 - Chrome
 - v97.0.4692.99 

**Smartphone (please complete the following information):**

**Additional context**
Content item not showing on stream: Recent Subscribers

**Comment by RapBlueSteel** [comment]
it seems to be working fine on my last stream but i will keep monitoring. thanks!

**Comment by marcandrews** [comment]
OK cool let me know. Other uses have reported this fixed as well, but if it happens again, signing out and signing back into Overlay Expert with Twitch usually resolves it too.

Closes #243.
