### ISSUE TITLE
Overlay animation

### ISSUE THREAD

**Issue by Riska117** [overlay-expert/help-desk#245]
Hi. Im using your overlays to show who the last follower and subscriber is on screen. Is there a way to turn off the animation which makes it go from right to left and instead just keep it still? I dont want the constant animation on my overlays :)

**Comment by marcandrews** [comment]
If the text does not fit the layer, it will automatically scroll.

If you do not want it to scroll, increase the width of the layer or reduce the number of followers listed by following the instructions in this tweet https://twitter.com/OverlayExpert/status/1285351921864368133.

**Comment by Riska117** [comment]
Aaah i see thank you! I have Also a «latest sub» overlay, but there is the
subcount behind the name of the latest subscriber aswell. How do i remove
the subcount behind?
