### ISSUE TITLE
Can´t use other alert rather than Twitch Follow

### ISSUE THREAD

**Issue by jzaball16** [overlay-expert/help-desk#246]
**Describe the bug**
Hi. I´m having an issue with my Overlay Expert. Everytime I try to set up a non-Twitchfollow alert, I get an error an it doesn´t work properly. Neither the follow alert or the suscriber, etc.

**To Reproduce**

1. Go to 'alert'
2. Click on 'Event Based'
3. Select 'Twtich suscribe"

**Expected behavior**
I try to set up my alerts for suscribe, host, raid, etc. But nothing works properly, not even the follow alert.

**Twitch channel**
https://twitch.tv/jzaballa16_

**Screenshots**
![image](https://user-images.githubusercontent.com/98853066/152060936-91eedfd5-630e-485d-9df0-6628c742081d.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [97]

**Smartphone (please complete the following information):**
 - Device: [Nubia Red Magic 3]
 - OS: [Android 7]
 - Browser [Chrome]
 - Version [97]

**Additional context**
As far as I know I´m not the only one with this issue and I´m trying to figure it out. I stream on a ps5 and my friendo on a ps4. The Overlay works perfectly and if we only use the follow alert it works. But if we try to add some new allert or use only one diferent from follow it brokes

**Comment by jzaball16** [comment]
What else do you nerd?😂

**Comment by marcandrews** [comment]
Sorry for the belated reply.

Can you try signing out and signing back into Overlay Expert with Twitch?
