### ISSUE TITLE
Overlay was working yesterday, down today

### ISSUE THREAD

**Issue by LordTussaud** [overlay-expert/help-desk#248]
**Describe the bug**
I was able to use my overlays when I was doing test streams yesterday on my account. Currently I am not getting any overlays on my stream. (I am streaming from Xbox, and managing from Laptop). I have the overlay set to overlay 1 and I have tried multiple of my overlays. 

**To Reproduce**
1. Selected my overlay in config
2. Launched my stream 
3. Overlay is not appearing 

**Expected behavior**
When I start up my stream I expected my overlay to appear in my stream manager. It is a basic overlay with only a background and a twitch chat. 

**Twitch channel**
https://twitch.tv/lordtussaud

**Screenshots**
<img width="780" alt="image" src="https://user-images.githubusercontent.com/99223810/152889495-62704405-ec5a-412c-85f8-151290d029e2.png">
 
<img width="912" alt="image" src="https://user-images.githubusercontent.com/99223810/152889552-66cd16ef-11b1-4bfa-ac12-7d97db334687.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version Version 98.0.4758.80

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version N/A

**Additional context**
The overlay was functioning yesterday and on Friday when I launched the extension for my stream. Yesterday I verified while trying to set up a "BRB" screen and the overlay worked just not the chat toggles. Now the overlay itself isn't working.

**Comment by itzwaldeaux** [comment]
i am having the same issue.

**Comment by Amazingpanda97107** [comment]
is everything back up and running?

**Comment by natefowler34** [comment]
I'm also having this issue. I can't load my overlay. It's saying error.

**Comment by Amazingpanda97107** [comment]
is it back down again???

**Comment by itzwaldeaux** [comment]
i haven't tried yet

**Comment by marcandrews** [comment]
The Twitch API is out again. We have an extension update pending to help with this issue, but it is still under review by Twitch.

**Comment by Amazingpanda97107** [comment]
is it back up? Anyone test?

**Comment by itzwaldeaux** [comment]
it is working right now

**Comment by Amazingpanda97107** [comment]
Amazing! thank you!

**Comment by LordTussaud** [comment]
Hello Team, 

I just tested my overlays in preparation for my stream tonight and it looks like I am back up and running!

**Comment by marcandrews** [comment]
Thanks for the update @LordTussaud 💜 

We will keep this ticket open until the extension is updated.

**Comment by LordTussaud** [comment]
Hello like I said the overlay is appearing now, however I am running into a small issue with my chat box I have implimented? Would you prefer this in a different bug report? I should be able to just use the chat feature on my laptop itself for my stream tonight and just hide the layers on my overlay until I can get this sorted.

<img width="372" alt="image" src="https://user-images.githubusercontent.com/99223810/153673415-949f288d-bf76-47f1-82b0-e662e921b76e.png">

**Comment by Amazingpanda97107** [comment]
any updates on the extension? i know there is going to be an outage for 4 hrs today but last time it lasted all day, should we expect that today?

**Comment by hanakowastaken** [comment]
I keep having an error code any time I try to use my custom overlay.

**Comment by hanakowastaken** [comment]
> I keep having an error code any time I try to use my custom overlay.

![Uploading Screenshot 2022-02-14 142916.jpg…]()

**Comment by hanakowastaken** [comment]
> I keep having an error code any time I try to use my custom overlay.

![Screenshot 2022-02-14 142916](https://user-images.githubusercontent.com/99686008/153934009-4a9aff24-10ea-495b-83b1-72a301f3efca.jpg)

**Comment by marcandrews** [comment]
We were able mitigate almost all of the issues with respect to the scheduled Twitch API outages, with exception to the Twitch Chat Widget. The Twitch Chat Widget will not function during the scheduled outages and will require an extension update that is currently under review by Twitch. We are monitoring the situation and apologize for the inconvenience.

**Comment by DariusMills** [comment]
I am still receiving the same error message, any estimate as to when this will be fixed?

**Comment by marcandrews** [comment]
I tested choosing overlays from the extension configuration screen and it is working. If you are having issues choosing overlays from the configuration screen, please join our Discord (https://discord.com/invite/bhJThkq) so we can debug your issue.

**Comment by marcandrews** [comment]
@hanakowastaken @DariusMills for the extension configuration issue, please see #257.

**Comment by itzwaldeaux** [comment]
The overlay is not working again.

**Comment by ThomasKing1** [comment]
The overlay is not working as well, logged in, created the overlay, added the extension but when selecting my overlay it gives me an error

**Comment by Amazingpanda97107** [comment]
Any news on the Extension Update?

**Comment by marcandrews** [comment]
The extension is still under review unfortunately. Twitch made a whole bunch of breaking changes this month so everyone is trying to update their apps so I imagine they have quite the backlog.

**Comment by Charlyem931** [comment]
I have de same problem

**Comment by ixAshleyyy** [comment]
Im having the same problem and nothing works

**Comment by marcandrews** [comment]
This is resolved.

**Comment by itzwaldeaux** [comment]
Same issue is occurring. My overlay does not work.

**Comment by marcandrews** [comment]
If you are still experiencing issues, please see https://github.com/overlay-expert/help-desk/issues/104; otherwise create a new issue.
