### ISSUE TITLE
For some reason my custom overlay is not being Displayed while live on PC | Recent as of Today

### ISSUE THREAD

**Issue by brycegreene20** [overlay-expert/help-desk#253]
This bug has been recent as of today. Every time in the past my custom overlay worked until I made changes on my laptop, now whenever I go live my overlay does not popup. The changes consisted of different text group contents that linked with twitch. Like adding "Recent Follows" to pop up and what not.

 Of course, I can see, edit, and save my overlay in configuration settings. It is also selected. I can even preview it with the recent test streams I have been doing using the Overlay extension. But whenever I go live, the overlay components popup on the right hand of the screen. But neither my viewers or I from stream manager can see my custom overlay popup regardless of the side drawer icons that popup. I have tried clearing caches, resetting passwords, disabling ad blocks, and even updating and restarting my computer. nothing seems to work. Please advise.

Please see view from stream manager   
![Capture](https://user-images.githubusercontent.com/67281298/153356278-bed962d3-ebc6-4822-a411-a98f23feac2f.PNG)

@marcandrews #248 #251

**Comment by marcandrews** [comment]
Duplicates #248
