### ISSUE TITLE
Updating in real time

### ISSUE THREAD

**Issue by BluesDebut** [overlay-expert/help-desk#256]
**Describe the bug**
I have noticed that the overlay i'm using doesn't update its info in real time which us a huge inconvienence. It seems that some aspects of the overlay don't work as well, namely the pop up that should appear when someone follows my channel.

**To Reproduce**

**Expected behavior**
I expect real-time updates for my channel statistics and for pop ups to work like they should.

**Twitch channel**
https://twitch.tv/BluesDebut

**Screenshots**
[e.g. Builder, Extension Configuration Screen, etc.]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Amazingpanda97107** [comment]
im having this issue with my recent subscribers? ive refreshed. logged out and back in. logged in and out of twitch. ive deleted the layer and made another one and its still the same names on the subs list. ive gotten new subs and they have not shown up on the list its always the same names. i think one of them isn't even subbed anymore. is this going to be fixed? Twitch - TheAmazingPandah

**Comment by marcandrews** [comment]
@Amazingpanda97107 please make a new issue.
