### ISSUE TITLE
Error encountered when choosing an overlay in the extension configuration screen

### ISSUE THREAD

**Issue by GeeklingNo1** [overlay-expert/help-desk#257]
**Describe the bug**

When I try to configure the extension from the twitch dashboard a window appears that says 'an error was encountered. Please try again. If the problem persists contact us.' If I close the error window and attempt to select an overlay the window reopens. I can edit and add overlays but cannot select them for use.

**Attempted troubleshooting**

reopened twitch
reinstalled extension
tried again later

**To Reproduce**

dashboard>extensions>my extensions>configure>error message

**Expected behavior**

Chose an overlay to apply to stream

**Twitch channel**

https://www.twitch.tv/geeklingno1

**Desktop (please complete the following information):**

 - OS: macOS 11.6.1
 - Browser: Chrome

**Comment by marcandrews** [comment]
Duplicates #248

**Comment by PynkyB00** [comment]
[GeeklingNo1](https://github.com/GeeklingNo1) I'm having the same issue

**Comment by marcandrews** [comment]
This is a bug.

**Comment by Kirbogod** [comment]
Have the same issue. Twitch user is ze_holy_kirb.

**Comment by daddymac2004** [comment]
i also have this issue it is  today issue based on how many people have the same problem at the same time but if it helps my twitch it @daddymac2004

**Comment by xxcobrakai94xx** [comment]
I have the same problem. 

Twitch: xxcobrakai94xx

**Comment by Jaggie99** [comment]
Getting error as well Twitch: Jaggie

**Comment by MoodiPanda** [comment]
I'm getting an error aswell,  I tried to "Choose" my Overlay on Google Chrome, Internet explorer, Firefox and IOS Browser and im getting "An error was encountered. Please try again. If the problem persists, please contact us."  I even tried to "Choose" a Blank overlay and Im still getting an error   Twitch: MoodiPanda

**Comment by blackfoot6r** [comment]
I am receiving the same issue twitch username is blackfoot6r

**Comment by PynkyB00** [comment]
> This is a bug that will require an update to the extension.
> 
> If you are experiencing this issue, please reply with your Twitch username and we will fix it as soon as we can.

PynyB00

**Comment by jipperjap** [comment]
I am having the same issue, twitch username : jipperjap

**Comment by litoxx5** [comment]
I am having the same issue, twitch username : starelix

**Comment by Vibemez** [comment]
I have the Same Issue It keeps happening Everytime when I try to click it my Twitch Is : L409R

**Comment by marcandrews** [comment]
For anyone experiencing this issue, please see https://twitter.com/OverlayExpert/status/1493704522279096326.

**Comment by marcandrews** [comment]
This issue is now resolved.

**Comment by Power-rangerX** [comment]
cant activate the extension on firefox, using PC. i tried using my mobile phones  firefox on Android as well, but does the same thing.
