### ISSUE TITLE
Overlay Expert configure error

### ISSUE THREAD

**Issue by NMRStatik** [overlay-expert/help-desk#259]
**Describe the bug**
When i click on choose it gives me an error

**To Reproduce**
1. Go to '..overlay expert.'
2. Click on '...configure.'
3. Scroll down to '.choose...'

**Expected behavior**
To click on choose and it say selected
**Twitch channel**
https://twitch.tv/nmrstatik

**Screenshots**
[e.g. Builder, Extension Configuration Screen, etc.]

**Desktop (please complete the following information):**
 - Browser google chrome microsoft edge

**Smartphone (please complete the following information):**

**Additional context**

**Comment by NMRStatik** [comment]
please help

**Comment by xxcobrakai94xx** [comment]
I have the same 

Twitch: xxcobrakai94xx

**Comment by marcandrews** [comment]
Duplicates #258

**Comment by elitehumanity** [comment]
Same issue here 2 days. Twitch SammyPresser199
