### ISSUE TITLE
Images are not showing on stream

### ISSUE THREAD

**Issue by MoodiPanda** [overlay-expert/help-desk#260]
**Describe the bug**
Images are not showing on stream , I tried three different Overlay templates and tried creating one with only a "Background" and none of them show up in stream not even the BrB screen, The only thing that shows is the TEXT you can add from the overlay builder.

**To Reproduce**
1. Go to https://overlay.expert/overlays
2. Click on 'Select for Extension' on 3 different  overlays
3. Go to twitch.tv/MoodiPanda   "Logged In and Logged out"
4. No Images show on stream ONLY Text from overlay builder.

**Expected behavior**
I expected to see the Overlay image appear on stream.

**Twitch channel**
https://twitch.tv/MoodiPanda

**Screenshots**
![Screenshot_2022-02-15  rust overlay  saved  · Builder · Overlay Expert](https://user-images.githubusercontent.com/99734771/154192161-7f3f44c5-fb35-46e7-928d-b35202d76a9f.png)
![Screenshot-2022-02-15-Twitch-1](https://user-images.githubusercontent.com/99734771/154192174-ed871a49-39a9-4580-b292-7dc49f8f49d8.png)
![Screenshot_2022-02-15  test  modified  · Builder · Overlay Expert](https://user-images.githubusercontent.com/99734771/154192188-524c847f-8152-48cf-8f9f-80667abe9c98.png)
![Screenshot_2022-02-15 Twitch](https://user-images.githubusercontent.com/99734771/154192218-3ad00f33-c8f5-42ee-b7ce-d474c9ab2cec.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10, Iphone XR, Windows 7]
 - Browser [Google Chrome, FireFox]
 - Version [Up to Date]

**Additional context**
Made a Test Overlay with only a "Background"  1920x1080 and even 1280x720 aswell

On GOOGLE CHROME the grey text on the top of the screen dosn't show either its completely blank.

**Comment by MoodiPanda** [comment]
Hello? Any way to fix this? its been 2 days and no reply

**Comment by marcandrews** [comment]
Image loading is working. Try checking your browser's privacy and security settings and enabled third-party cookies.

**Comment by MoodiPanda** [comment]
> Image loading is working. Try checking your browser's privacy and security settings and enabling third-party cookies.

I got it to work thank you
