### ISSUE TITLE
error with configuring

### ISSUE THREAD

**Issue by Penguleesi** [overlay-expert/help-desk#261]
**Describe the bug**
When i try to choose a overlay it just says error. I have logged out and in, refreshed web browser, and run on chrome

**To Reproduce**
1. Go to Overlay expert (already installed)
2. Click on choose overlay
3. See error

**Expected behavior**
The overlay to attach to my channel

**Twitch channel**
https://twitch.tv/Penguleesi

**Screenshots**
[e.g. Builder, Extension Configuration Screen, etc.]

**Desktop (please complete the following information):**
 - OS: Microsoft windows
 - Browser chrome
 - Version 98.0.4758.102 

**Smartphone (please complete the following information):**

**Additional context**
I thought it may fix itself if i bought a overlay and it didn't

**Comment by marcandrews** [comment]
Duplicates #257
