### ISSUE TITLE
alerts not working

### ISSUE THREAD

**Issue by natefowler34** [overlay-expert/help-desk#262]
**Describe the bug**
my alerts are not showing up when they should be (subs, follows, etc.) I have even tried to preview them in the overlay website and I am getting an error. 

**Expected behavior**
I, and viewers, am/are  expecting to be able to see these alerts

**Twitch channel**
https://www.twitch.tv/natefowler34

**Screenshots**
no screenshots 
**Desktop (please complete the following information):**
chrome browser to edit overlays but using twitch extension

**Smartphone (please complete the following information):**
android but use laptop for extension

**Comment by marcandrews** [comment]
This should be resolved now. Can you confirm?
