### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lolpariah** [overlay-expert/help-desk#265]
**Describe the bug**
every time i click on choose overlay i get a error code

**To Reproduce**

**Expected behavior**

**Twitch channel**
https://twitch.tv/lolzpariah

**Screenshots**
[e.g. Builder, Extension Configuration Screen, etc.]
![Screenshot 2022-02-17 11 40 17 PM](https://user-images.githubusercontent.com/99941612/154618856-9f3fc615-dd02-4910-9fc4-ae0534513a41.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by OrcaStreaming** [comment]
I am having the same exact problem.
