### ISSUE TITLE
cannot select

### ISSUE THREAD

**Issue by sayonarakyodai** [overlay-expert/help-desk#267]
I had installed the extension in hopes of having a quick easy and simple overlay but after creating an overlay my twitch has an error selecting and using said overlay

i have tried to reset my browser
refresh my page several times
un and re installed the browser 
nothing has worked thus far

i expected after installing creating and activating to have a functioning extension

https://twitch.tv/sayonara_kyodai

O.S: 18362.720
Google Chrome

**Comment by marcandrews** [comment]
Duplicates #257
