### ISSUE TITLE
Getting an error when choosing an overlay 

### ISSUE THREAD

**Issue by 101zeroyty** [overlay-expert/help-desk#268]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Twitch channel**
https://twitch.tv/username

**Screenshots**
[e.g. Builder, Extension Configuration Screen, etc.]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by marcandrews** [comment]
Duplicates #257
