### ISSUE TITLE
when selecting overlay getting error message 

### ISSUE THREAD

**Issue by ethanfrrr** [overlay-expert/help-desk#270]
when I try to choose an overlay it gives me an error message I have done all the troubleshooting I can and still won't work
**To Reproduce**
1. Go to choose an overlay
2. Click on choose
3. See an error

**Expected behavior**

**Twitch channel**
https://twitch.tv/ethanfrrr

**Screenshots**
[e.g. Builder, Extension Configuration Screen, etc.]

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome

**Comment by marcandrews** [comment]
Duplicates #257
