### ISSUE TITLE
wont let me save my overlay 

### ISSUE THREAD

**Issue by frenchman669** [overlay-expert/help-desk#271]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Twitch channel**
https://twitch.tv/username

**Screenshots**
[e.g. Builder, Extension Configuration Screen, etc.]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by marcandrews** [comment]
Duplicates #232
