### ISSUE TITLE
payed 20 dollars on a animated overlay but it doesn't  save to the extension in the creator board on twitch  just the website 

### ISSUE THREAD

**Issue by Ajayplays** [overlay-expert/help-desk#274]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always
frustrated when [...]    so i bought the animated overlay and every time i try to save it and go to the creator dashboard to  add it to the channel it never appears on the saved overlays it just appears on the website not the extension 

**Describe the solution you'd like**
A clear and concise description of what you want to happen. is there a way that can be fixed?

**Screenshots**

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've
considered.
  Twitch  https://www.twitch.tv/ajayplays_

**Additional context**

**Comment by marcandrews** [comment]
Duplicates #26
