### ISSUE TITLE
Overlay Expert "choose" bug

### ISSUE THREAD

**Issue by SonOfAnderchy** [overlay-expert/help-desk#276]
-->

When trying to select "choose" on an overlay within the twitch extensions, I get an error message.

**To Reproduce**
1. Go to: Configure
2. Click on: Choose
3 See error

**Twitch channel**
https://twitch.tv/sonofanderchy

**Screenshots**
![image](https://user-images.githubusercontent.com/100162974/155020527-4911eeaf-a372-46b8-b7fd-deb9fc12ae60.png)

**Desktop (please complete the following information):**
 - OS: ChromeOS
 - Browser: Chrome
 - Version: 98.0.4758.91

**Comment by kittyy302** [comment]
I am also having the same issue 
twitch: kittyy302

**Comment by marcandrews** [comment]
Duplicates #257

**Comment by Jonnerz** [comment]
Same issue here
Twitch: whoiskillrob

**Comment by Letshavefunandplay** [comment]
I am also having the same issue when choosing an overlay

Twitch: twitch.tv/Letshavefunandplay
OS: Windows 11
Browser: Edge 79+
