### ISSUE TITLE
Everytime I try to use a overlay it keeps giving me an error screen it's been over a week and i've tried everything please

### ISSUE THREAD

**Issue by ROZ3T** [overlay-expert/help-desk#277]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Twitch channel**
https://twitch.tv/username

**Screenshots**
[e.g. Builder, Extension Configuration Screen, etc.]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by marcandrews** [comment]
Duplicates #257
