### ISSUE TITLE
When I want to chose overlay for twich , I can`t and he writes to me that he have error how i can fix that ?

### ISSUE THREAD

**Issue by fddfasdsda** [overlay-expert/help-desk#278]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Twitch channel**
https://twitch.tv/username

**Screenshots**
[e.g. Builder, Extension Configuration Screen, etc.]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by marcandrews** [comment]
Duplicates #257
