### ISSUE TITLE
error when choosing overlay for twitch extension

### ISSUE THREAD

**Issue by maceface2111** [overlay-expert/help-desk#280]
**Describe the bug**
i purchased an overlay from overlay expert when "choosing" the overlay i recieve an error an to contact you guys

**To Reproduce**
go to overlay expert on twitch 
then hit choose on purchased overlay
error code comes up

**Expected behavior**
after choosing i would expect to see the overlay to pop up on my stream

**Twitch channel**
https://twitch.tv/maceface2111

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome

**Comment by TTVCloverGaming** [comment]
Mine Is doing the exact same thing as well

**Comment by marcandrews** [comment]
Duplicates #257

**Comment by TTVCloverGaming** [comment]
I'm having the same issue Twitch Clovergaming_
