### ISSUE TITLE
Not able to Choose Any Overlays not even the one I created. I keep getting message to contact support.

### ISSUE THREAD

**Issue by itskingopa** [overlay-expert/help-desk#284]
Not able to Choose Any Overlays not even the one I created. I keep getting message to contact support.

https://twitch.tv/zanopa

![Screen Shot 2022-02-25 at 9 38 10 AM](https://user-images.githubusercontent.com/100422201/155733909-7dd19892-df42-4d41-a779-f55007d1618c.png)

**Comment by LilChrisCuh** [comment]
I keep getting this as well. would be great to have an answer for this issue

**Comment by itskingopa** [comment]
Go to your overlays in overlay expert and choose it from there. When you go
back to your Twitch you'll see it been selected.
