### ISSUE TITLE
OverlayExpert: Test Message

### ISSUE THREAD

**Issue by JOBOsmiles** [overlay-expert/help-desk#286]
**Describe the bug**
When editing my overlay, a popup comes from each layer saying "OverlayExpert: Test Message" stamped with the date and time. They keep popping up.

**To Reproduce**
1. Go to Edit overlay
2. See error

**Expected behavior**
these test messages should not even be there

**Twitch channel**

https://twitch.tv/jobosmiles

**Screenshots**

![Screenshot 2022-02-25 9 02 57 PM](https://user-images.githubusercontent.com/100114977/155828210-d5599ec8-a8ef-4b93-9ac0-d41acd6df15f.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Chromebook
 - Browser [e.g. chrome, safari] chrome 
 - Version [e.g. 22] 98.0.4758.107 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by marcandrews** [comment]
How would you style and position your chat boxes without the test messages there?
