### ISSUE TITLE
Overlay expert staying unlocked on Lightstream and alerts not working

### ISSUE THREAD

**Issue by thetravisparrish** [overlay-expert/help-desk#293]
PLEASE SEARCH BEFORE CREATING A NEW ISSUE.

  Please use the following issue template to provide information about the bug
  you are experiencing. The more information you provide, the faster your issue
  can be resolved.

  INCOMPLETE BUG REPORTS WILL BE IGNORED.
-->

### Describe the bug

  Please provide a clear and concise description of what the bug you are
  experiencing. Add any other context about the problem too.

  Type below this arrow -->

Im using a chrome book for my stream on console overlay expert wants me to unlock code every stream even with the remember for two weeks box checked. Also no alerts are working. Like latest follower and new host or raid.

### To Reproduce

1. Go to 'overlay expert unlock'
  2. Click on ‘remember for two weeks'
  3. Scroll down to 'enter unlock code'
  4. See overlay is not unlocked next time i try to stream

### Expected behavior

For the overlay to be unlocked for at least two weeks and alerts to work properly  

### Twitch channel

TheTravisParrish 
### Screenshots

 none
- OS:  none
- Browser:  none

**Comment by thetravisparrish** [comment]
I’m using a chrome book and overlay expert is wanting me to unlock every time I stream. Even with the remember for two weeks checked.

**Comment by marcandrews** [comment]
Please search before creating a new issue.

This issue is already discussed in #183; please see this issue for more information.
