### ISSUE TITLE
Can't add the overlay to my stream

### ISSUE THREAD

**Issue by JohnDaHaitian** [overlay-expert/help-desk#296]
### Describe the bug

When I try to add my customized overlay to my stream. It keeps showing me an error message saying "Error, An error was encountered. Please try again. If the problem persists, please contact us." I am now contacting you guys about this issue. I want to know what the problem is and what I can do to fix it because I have tried every option that you guys have given me to solve the issue on the support page but they all came back negative. Please help ASAP.
### To Reproduce

1. Go on the extension and make your own overlay or the same one as mine, which is Carbon Fiber Orange theme,
2. Edit it however you want it to be and then save it
3. go to your stream manager page and open the extension and choose the overlay that you have just created
4. and BAM! You have found the error
### Expected behavior

What I expected to happen was: the overlay being added to my stream and placed to be seen by everyone watching the stream
### Twitch channel

.https://twitch.tv/johndahaitian
### Screenshots

![error note](https://user-images.githubusercontent.com/100744612/156290252-d899afda-0cc2-4b6f-9f9c-3341bbcdb248.png)

### Device (PC, mobile, etc.):

- Device: PC
- OS: Windows 10
- Browser: Chrome & Microsoft Edge

**Comment by alphaguss** [comment]
I have the same error

**Comment by marcandrews** [comment]
Please search before creating a new issue.

This issue is already discussed in #257 please see this issue for more information.
