### ISSUE TITLE
My choose button won't work

### ISSUE THREAD

**Issue by Slappn** [overlay-expert/help-desk#298]
-->

### Describe the bug
![Screenshot (1)](https://user-images.githubusercontent.com/100746344/156293997-2374e95c-954c-4767-a677-6476546499ed.png)
When i try to choose my custom overlay this appears and it has been showing up since yesterday. I've tried on mobile but it doesn't work, tried it on a Explorer and other sites, but a no go. hopefully this can be fixed or so on...

### Device (PC, mobile, etc.):

- Device: 
- OS: 
- Browser:

**Comment by marcandrews** [comment]
Please search before creating a new issue.

This issue is already discussed in #257 please see this issue for more information.
