### ISSUE TITLE
my overlay wont work i select it and hope for it to work but it doesnt and i worked hard on it and its very disappointing how I cant use it 

### ISSUE THREAD

**Issue by BIGGIEK** [overlay-expert/help-desk#299]
im not happy that i cat use the over lay for my twitch and I worked on it for serval hours trying to figure out how it works just to not be able to use it i want to use it so my streams can look better!!!

**Comment by marcandrews** [comment]
Please search before creating a new issue.

This issue is already discussed in #257 please see this issue for more information.
