### ISSUE TITLE
Overlay Expert choose button won't work.

### ISSUE THREAD

**Issue by xRussianDemonxPR** [overlay-expert/help-desk#300]
**The choose button is not working for me.** I've tried several ways and it still doesn't work. Entere from different internet pages such as Safari, Google and Microsoft Edge. I tried doing it from my computer and tablet still won't let me choose anything Uninstall and reinstall doesn't work for me. I tried all the instructions that the page gives me and it still doesn't work for me.
![4affddef-629a-413b-bc11-0f4a4e6306a2](https://user-images.githubusercontent.com/100732699/156405741-5d88de76-aced-4446-a4e9-407bf31f5af3.jpg)

**Comment by marcandrews** [comment]
Please search before creating a new issue.

This issue is already discussed in #257 please see this issue for more information.
