### ISSUE TITLE
i paid for an overlay in overlay expert and everytime i choose it it says it had encountered a problem i go to support page and still no help

### ISSUE THREAD

**Issue by ninoskyye** [overlay-expert/help-desk#302]
### Device (PC, mobile, etc.):

- Device: 
- OS: 
- Browser:

**Comment by TheTruRoninYt** [comment]
Im having the same issue when i press choose it wont allow me to select it and gives me an
![Capture](https://user-images.githubusercontent.com/100964043/156827489-994c6789-dc08-43c0-9fd3-8e65522ca076.PNG)

**Comment by danjkg** [comment]
this keeps popping up for me even when i try using the free ones

**Comment by splits20** [comment]
Same

**Comment by marcandrews** [comment]
Please search before creating a new issue.

This issue is already discussed in #257 please see this issue for more information.
