### ISSUE TITLE
Overlay issues

### ISSUE THREAD

**Issue by madsquirter** [overlay-expert/help-desk#303]
Hi I just spent approx 4 hours creating an overlay and it was saving fine at the start. Then I started having issues saving the overlay. I exited the overlay and opened it back up. I had lost approx 2 hours of work so I started back on the project and was saving fine again until about 2 steps into a layer (I was saving very regularly at this stage), and it stopped again.
I exited, reloaded and decided to not add 3 layers that I had previously done and saved/exited.
I now have tried to "choose" the overlay after activating it on my twitch extension as overlay 1 and comes up with the notification "An error was encountered. Please try again. If the problem persists, please contact us". I have tried deactivating and reactivating, and tried editing but now I can't even edit the overlay.
Please help so that I haven't wasted 5 hours of my day.
Thanks
Matthew Birtwistle

**Comment by marcandrews** [comment]
Please search before creating a new issue.

This issue is already discussed in #257 please see this issue for more information.
