### ISSUE TITLE
wont let me choose my overlay

### ISSUE THREAD

**Issue by itzyaboycole** [overlay-expert/help-desk#305]
### Device (PC, mobile, etc.):

- Device: 
- OS: 
- Browser:

**Comment by ixAshleyyy** [comment]
I'm having the same problem

**Comment by dylanfenn** [comment]
same when i press choose it gives me a link here

**Comment by ixAshleyyy** [comment]
Yea, and they are saying they fixed it but it doesn't even work.

**Comment by marcandrews** [comment]
Please search before creating a new issue.

This issue is already discussed in https://github.com/overlay-expert/help-desk/issues/257; please see this issue for more information.
