### ISSUE TITLE
Expert Overlay "Choose" Not an Option

### ISSUE THREAD

**Issue by waaamps** [overlay-expert/help-desk#307]
I got as far as making my overlay on Twitch but when I go to choose it or any of the other free ones, it pops up a screen that says "An error was encountered. Please try again. If the problem persists, please contact us. I've tried refreshing, restarting, deleted and reinstalled the extension. I'm on my HP laptop. Please help. Thanks in advance.

**Comment by Charlyem931** [comment]
I have the same trouble, my twitch channel is : premedrain
