### ISSUE TITLE
Unable to choose overlay

### ISSUE THREAD

**Issue by JazzGal13** [overlay-expert/help-desk#308]
Whenever I want to choose an overlay, a pop-up comes up with this message: "An error was encountered. Please try again. If the problem persists, please contact us."

**Comment by JayHighDaKing** [comment]
im having the exact same problem, even after i spent hours customizing my own...

**Comment by marcandrews** [comment]
Please search before creating a new issue.

This issue is already discussed in https://github.com/overlay-expert/help-desk/issues/257; please see this issue for more information.
