### ISSUE TITLE
I press choose on the overlay i want to use and it gives me an error message that i need to contact help desk. i purchased my overlay and it will not work. please help ive tried all things listed as possible troubleshoot

### ISSUE THREAD

**Issue by DiamondDabbin** [overlay-expert/help-desk#309]
### Device (PC, mobile, etc.):

- Device: 
- OS: 
- Browser:

**Comment by DiamondDabbin** [comment]
An error was encountered. Please try again. If the problem persists, please contact us, 

I have recieved this error on my mobile on chrome web browser, on my laptop using chrome and on edge both with the newest versions of the web browser. 

Twitch channel DiamondDabbin

**Comment by kmanan** [comment]
Still getting this error. Looked at that "workaround" Twitter thread. There is no workaround.

**Comment by DiamondDabbin** [comment]
How do we resolve this? I paid for this overlay

**Comment by marcandrews** [comment]
To choose a purchased overlay, please see this tweet https://twitter.com/OverlayExpert/status/1501996040161005572

More information can be found in issue #257.

**Comment by DiamondDabbin** [comment]
Why would you close this if its not resolved?

**Comment by marcandrews** [comment]
It is closed because the workaround is shown in the video attached to the tweet and it is a duplicate of https://github.com/overlay-expert/help-desk/issues/257.
