### ISSUE TITLE
cannot activate overlay

### ISSUE THREAD

**Issue by gnilkeeg** [overlay-expert/help-desk#310]
### Screenshots

![2022-03-09 (1)](https://user-images.githubusercontent.com/101287864/157515138-50693dd5-a5d9-4c5b-abfc-0f7863108f62.png)

  Type below this arrow --> 

when i try to activate my overlay it says "an error has occurred try again if the problem persists coontact support" ,
not even a small loading

- Device:PC
- OS:Windows 11
- Browser:Chrome

**Comment by smck21** [comment]
same thing is happening to me

**Comment by kmanan** [comment]
Same error. No idea what to do or what it means. No clarity on what the error is.
