### ISSUE TITLE
Overlay not working

### ISSUE THREAD

**Issue by kmanan** [overlay-expert/help-desk#312]
This is not a workaround. Being a rude person telling people to "search" before posting is a terrible way to approach a problem. Especially when the workaround is a tweet that does not address the issue. 

For anyone experiencing this issue, please see https://twitter.com/OverlayExpert/status/1493704522279096326.

_Originally posted by @marcandrews in https://github.com/overlay-expert/help-desk/issues/257#issuecomment-1040833629_

**Comment by marcandrews** [comment]
What is the issue?

**Comment by marcandrews** [comment]
Did you watch the video attached to the tweet?

**Comment by kmanan** [comment]
Yep. “Customized” the overlay, saved it, it shows up in my overlay list but there’s no 3 dot to apply. So it’s been a bit confusing on how to get a marketplace overlay to work.

Regards,
Manan Kakkar
________________________________

**Comment by marcandrews** [comment]
Please go to https://overlay.expert/overlays, sign in if you are not already signed in, and post a screenshot.

**Comment by TealSpider** [comment]
it what let me chose it on my twich

**Comment by marcandrews** [comment]
To resolve this issue, please see https://github.com/overlay-expert/help-desk/issues/257#issuecomment-1040833629.
