### ISSUE TITLE
overlay expert not working

### ISSUE THREAD

**Issue by brettniebishh** [overlay-expert/help-desk#313]
### Describe the bug
When i try to choose my custom overlay for overlay expert i am getting an error that says "An error was encountered. Please try again. If the problem persists, please contact us." 
there is nothing on this page or the support page that offers any help to this issue. Please let me know what the fix is ASAP.

### Device (PC, mobile, etc.):

- Device: 
- OS: 
- Browser:

**Comment by brettniebishh** [comment]
We have done all of the suggested fixes, but nothing has change and we are using good chrome and it won’t work still

**Comment by marcandrews** [comment]
To resolve this issue, please see https://github.com/overlay-expert/help-desk/issues/257#issuecomment-1040833629.
