### ISSUE TITLE
Everytime I attempt to choose an Overlay there is an error

### ISSUE THREAD

**Issue by santosssjs** [overlay-expert/help-desk#314]
### Device (PC, mobile, etc.):

- Device: 
- OS: 
- Browser:

**Comment by songve** [comment]
intento poner la extension de overlay y me sale error

**Comment by sucre-b** [comment]
Same here! I've created a very simple overlay and it appears in my overlay options under the extension but when I click "choose" it gives an error message to contact support. 

Twitch channel: sucre_b
MacBook Air, osMonterey, Google Chrome browser
![Screen Shot 2022-03-14 at 1 48 58 PM](https://user-images.githubusercontent.com/101594530/158240789-43444fa9-df61-41d9-bf0c-809e263b2fdb.png)

**Comment by marcandrews** [comment]
To resolve this issue, please see https://github.com/overlay-expert/help-desk/issues/257#issuecomment-1040833629.
