### ISSUE TITLE
unable to use extension

### ISSUE THREAD

**Issue by Obadawe** [overlay-expert/help-desk#316]
I installed the "overley expert" extension on twitch and created an overley for the webcam, but when I try to activate it it gives me an error message which makes it impossible to use the extension. I kindly ask you to solve the problem. Thank you

my twitch channel is: Obadawe

**Comment by Power-rangerX** [comment]
I cant activate it either. made overlay, selected it.   Now, if you try to activate the  extension, it just loads infinitly.
