### ISSUE TITLE
Overlay keeps disappearing

### ISSUE THREAD

**Issue by Blondielyns** [overlay-expert/help-desk#318]
Since Thursday (10th March) my overlay keeps disappearing when I am streaming. I am using OBS and have never had this issue before. I have to refresh the browser source when it goes and it will come back but I sometimes don't notice it is gone for a while. I have cleared my cache on both OBS and my web browser with no luck. Watching my vods back it is definitely gone until I refresh. Please help!

My Twitch is www.twitch.tv/BlondieLyns you will see in my latest vod that it will just go for no reason, no error message nothing.

**Comment by marcandrews** [comment]
What date, time and timezone will you be live next?

**Comment by Blondielyns** [comment]
Hi! I will be live again today are 7pm GMT. I was working from home yesterday and kept my OBS open and kept checking OBS  to see if the overlay disappeared and it didn't so I think it only happens when I am live which is strange because I have been using it for around 3 weeks with no issues and no changes to my settings.

**Comment by marcandrews** [comment]
I won't be able to stop by your stream today, but can you try signing out and signing back into Overlay Expert with Twitch and see if it happens again?

**Comment by Blondielyns** [comment]
Hi, I logged out and back into overlay expert. I then changed a few things on the overlay resaved it and recopied the link into OBS. It still happened throughout the stream. Its so weird because if I leave OBS open and check on it now and again the overlay stays but as soon as I stream it keeps disappearing.

**Comment by lowbowie** [comment]
Hi, unsure if this issue has been resolved or not but I'm also experiencing this issue. The downtime is completely random, my overlay will stay open for a while or nor long at all but it does consistently disappear which prompts me to need to refresh. Never had this issue before but it has been impacting my stream a lot. 
Hope a fix comes soon.

**Comment by marcandrews** [comment]
@lowbowie what's your Twitch username and when next are you streaming?

**Comment by Blondielyns** [comment]
No my issues has not been resolved. I tried logging out and back in  and it as still happening on my last stream. @lowbowie mine is the same no reason for it happening and I have to constantly watch my stream to refresh the overlay which is frustrating. Streaming again tonight so if it happens again I may have to just remove it 😭

**Comment by marcandrews** [comment]
@Blondielyns what are your PC specs and OBS version?

**Comment by Blondielyns** [comment]
@marcandrews I have 8gb ram , geforce GTX 1650 graphics card, intel core i5-9300h CPU. It worked for 3-4 weeks until my last 3 streams and nothing has changed in between. My OBS is 27.2.3 (64 bit). Thank you

**Comment by marcandrews** [comment]
We identified an issue with the Twitch Chat Widget and parsing certain emojis. If you are experiencing this issue, please remove the Twitch Chat Widget from your overlay until we can get this resolved.

**Comment by marcandrews** [comment]
This should be resolved.

**Comment by Blondielyns** [comment]
Thank you so much for stopping by my stream and fixing my overlay! It means the world. You're the best!
