### ISSUE TITLE
cant pick no overlays

### ISSUE THREAD

**Issue by gambit1332** [overlay-expert/help-desk#319]
### Describe the bug

i cant pick any overlays for my stream.
### To Reproduce

go to overlay expert click on overlay expert choose overlay
### Expected behavior

i expected for me to be able to choose my overlay or any overlay for that matter
### Twitch channel

Gambit1332
### Device (PC, mobile, etc.):

- Device: 
- OS: 
- Browser:

**Comment by gazgayboi92** [comment]
im having same problem after creating my own overlay

**Comment by marcandrews** [comment]
@gambit1332 @gazgayboi92 can you try to choose an overlay now?

**Comment by marcandrews** [comment]
Duplicates https://github.com/overlay-expert/help-desk/issues/257.
