### ISSUE TITLE
No sounds are working when streaming

### ISSUE THREAD

**Issue by DeadEdsGaming** [overlay-expert/help-desk#320]
Please provide a clear and concise description of what the bug you are
  experiencing. Add any other context about the problem too.

  Type below this arrow -->

On the Overlay Expert editing program I have managed to upload various alerts and also a theme tune that I made (I managed to put a theme tune on my starting soon and ending soon overlay by changing the .mp3 to .webm file via the background video layer) 

now... In the editor all the sounds from the alerts and the theme tune work as they should
but...  During my stream the Overlays show but the sound does not play

I found a little slider on the left hand side of my screen, that seems to be a volume control, but nothing happens when I turn it to max

I believe I have done the over lays properly because they work how they should in the editor so I am a little confused to why they wont work on stream the same way.

P.S. I have also made commands to turn on and off the starting soon and ending soon overlays.
within the 2 overlays I have put the music and sounds in a nested layer (although today I just swapped the image from the normal layer to the nested layer and put the theme tune on the normal layer... if that make sense) so ill let you know if that makes a difference

Please let me know if I can do anything else as the program is pretty simple and I don't think there is much else i can do at this stage.

### To Reproduce

 1. make sound track
 2. compress the audio to match 8mb
 3. change the track format from .mp3 to .webm
 4. add a new layer in overlay expert
 5. add video image via the background tab
 6. upload video
 7. click on tick and that will then appear 
 8. go to quick chat toggle and do the normal steps there
 9. add a nested layer
 10. Upload track via the background video 
 11. click tick on the ''video'' you just uploaded
 12. put volume between 70% to 100%
 13. click on the tick to go back to ''add new layer''
 14. click the same tick to go back to main screen
 15. then save
 16. after saving work wait for the cloud icon to appear with a tick 
 17. then test the toggled layer by going into your twitch chat and type in your toggle message (!SS or !ES for me) 
 18. music works, layers work, background works... great stuff.
 19. go live on twitch
 20. repeat number 17
 21. change overlay experts volume rocker
 22. backgrounds and layer work... no sound

### Expected behavior

Everything above to work as expected haha :D

### Twitch channel

 https://twitch.tv/deadedsgaming

### Screenshots

The overlays on overlay expert isn't recorded when the stream is over... so i cant upload anything to show you what I mean

### Device (PC, mobile, etc.):

- Device: samsung Z fold 3
- OS: Windows 11 
- Browser: Google Chrome on PC and Samsung mobile,  google desktop version 

(I switch between devices because the laptop isn't mine... but I have this issue on both devices. NOTE: I know overlay expert doesn't work on the mobile app... but it does on the desktop version, of the internet, on the mobile)

**Comment by DeadEdsGaming** [comment]
not everything i wrote is in this post... is that normal?? lol

**Comment by marcandrews** [comment]
Let us see what we can do, but usually, autoplaying audio is going to be difficult as Twitch mandates that all extensions start muted. In addition, browsers usually prevent audio from autoplaying before user interaction (that is why we ask the user to unmute the extension and interact).

Avoid typing in between the `<!--` and `-->` as it will be formatted as a hidden comment 😅

**Comment by DeadEdsGaming** [comment]
> Avoid typing in between the `<!--` and `-->` as it will be formatted as a hidden comment 😅

ah i see haha sorry... i have edited the post :D

**Comment by DeadEdsGaming** [comment]
> Let us see what we can do, but usually, autoplaying audio is going to be difficult as Twitch mandates that all extensions start muted. In addition, browsers usually prevent audio from autoplaying before user interaction (that is why we ask the user to unmute the extension and interact).
> 

This is what i have already done but unmuting before interacting :)

**Comment by marcandrews** [comment]
> unmuting before interacting

What do you mean? If you unmute the extension, you are _interacting_ with it.

The viewer must unmute the extension before the layer with the background music is toggled on with the chat command.

**Comment by DeadEdsGaming** [comment]
I was just relaying to you what you said about the muted extensions. 

When I start my stream, I have to wait for overlay expert to boot up, then when it does there is a volume slider on the left had some of the video viewer (the box showing my stream) I slide that up before I do my command to get noise on me starting soon overlay. 

Are you saying that all viewers have to use that slider too get sound from my theme tune and alerts??

I am really confused at this point haha 😄 

Would it help if you saw it on my stream? I have no other way to record it.

**Comment by marcandrews** [comment]
> Are you saying that all viewers have to use that slider too get sound from my theme tune and alerts??

Yes, all viewers must unmute the overlay to hear sounds. This is Twitch's policy.

Actually, it might be easier if I just stop by your stream. When next are you streaming?

**Comment by DeadEdsGaming** [comment]
Ok so new problem... I just went onto overlay expert editor and now the sounds are not working at all on here when they did before

**Comment by DeadEdsGaming** [comment]
I am actually streaming tonight at 2000 GMT

**Comment by marcandrews** [comment]
Closing this in favor of #325
