### ISSUE TITLE
Recent Subscribers and Recent Cheers Content Issue

### ISSUE THREAD

**Issue by RapBlueSteel** [overlay-expert/help-desk#322]
Hi,

Just want to report again about recent subscribers content and recent cheers issue not working on the overlay.

For recent sub, it is not showing the most recent data. Though, the recent cheers seems to be working while streaming but when editing the overlay, it flags an issue.

Please check.

Thanks,
RapBlueSteel

![image](https://user-images.githubusercontent.com/98797872/158959221-1f112340-174f-4d99-a8dd-c1c869c9299d.png)

**Comment by marcandrews** [comment]
Please set the Background > Opacity of those two layers to `1`.

The recent sub issue is known, see https://github.com/overlay-expert/help-desk/issues/290 for more information.
