### ISSUE TITLE
Raid alerts not working

### ISSUE THREAD

**Issue by Amazingpanda97107** [overlay-expert/help-desk#324]
### Describe the bug - Raid alert display name wont show up. 

 was editing my raid alert and now it won't show the raider name. it still counts correctly. i deleted the layer and redid it, logged out and logged back in. Wont show up on preview or when live.

### Expected behavior

 For my raid alert to display  the name

### Twitch channel

  https://twitch.tv/TheAmazingPandah

### Device (PC, mobile, etc.):

- Device: 
- OS: 
- Browser:  Chromebook

**Comment by marcandrews** [comment]
This will be fixed in the next update.

**Comment by Amazingpanda97107** [comment]
When is the next update?

**Comment by Amazingpanda97107** [comment]
If you guys ever need to sponsor someone you can always choose me. I always
direct people to the Extension anyway for those in need of an overlay with
no OBS.
