### ISSUE TITLE
Need to know please

### ISSUE THREAD

**Issue by ylilpuo** [overlay-expert/help-desk#326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Twitch username

ylilpup

### Expected Behavior

I have a overlay that I have made in obs studio but as it looks like a what would be called osu overlay, I cant adjust where I would want my stream to show or the size.

### Current Behavior

I have a overlay that I have made in obs studio but as it looks like a what would be called osu overlay, I cant adjust where I would want my stream to show or the size.

### Steps To Reproduce

I have a overlay that I have made in obs studio but as it looks like a what would be called osu overlay, I cant adjust where I would want my stream to show or the size.

### Device

Other

### Operating system

Windows

### Browser

Chrome

### Anything else?

![Untitled design](https://user-images.githubusercontent.com/102564960/160513488-cfbb829c-5e1c-48fd-bfc3-ac7ea7e2f1d3.png)

**Comment by marcandrews** [comment]
Are you using the Twitch Extension?
