### ISSUE TITLE
Fatal Error, Browser Source, Scale and Transparency Fields, incorrect field settings?

### ISSUE THREAD

**Issue by Krahazik** [overlay-expert/help-desk#329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Twitch username

Krahazik

### Expected Behavior

Expected to enter a transparency number and set transparency, say 80 (a number).

### Current Behavior

With 80 (a number) entered into the field, I receive an error under the field indicating that the field expected a number but received a string and the overlay can not be saved until the error is resolved. This can not be resolved by the user as any character entered, even a number, is apparently treated as a string.

### Steps To Reproduce

1. Create New Overlay
2. Attempt to set up a browser source.

### I am streaming from

PC/OBS

### I am viewing from

PC/macOS/Linux web browser

### Are you using the Twitch Extension?

No

### Web browser

Other

### Anything else?

Was my first attempt to set up an overlay to give the plugin a try.

![OverlayExpert Fatal Error 220428A](https://user-images.githubusercontent.com/97745982/165802388-9bcac12f-e497-4ff8-ac2c-88b3afc4bd4f.jpg)

**Comment by marcandrews** [comment]
This should be resolved now; please let me know if you are still having issues.

Thanks for reporting it and your patience.
