### ISSUE TITLE
Cant access my Overlay I purchased for 19.99 USD

### ISSUE THREAD

**Issue by yellowsthegoat** [overlay-expert/help-desk#331]
It wasnt letting me link my twitch account so i linked with facebook and now i cant use my overlay on my twitch! How do i get a refund?

**Comment by marcandrews** [comment]
What is the error when you try to link your Twitch account?

**Comment by yellowsthegoat** [comment]
It says its not verified but it has been for years, i made a new email and
linked it to my twitch and it allowed me to log in to my overlay expert
using my twitch.. i was still unable to use the overlay i purchased..

**Comment by marcandrews** [comment]
Is the email you use for Facebook the same as the one that you use for Twitch?

**Comment by yellowsthegoat** [comment]
Unfortunately not

**Comment by yellowsthegoat** [comment]
I cant access the email i use for my facebook.. will that be an issue?

**Comment by yellowsthegoat** [comment]
i signed in with facebook because it wouldnt let me sign in with twitch..

**Comment by marcandrews** [comment]
No, but you should update it to one to which you have access.

Let's continue this on our Discord https://discord.com/invite/bhJThkq.

**Comment by yellowsthegoat** [comment]
So can you deleted the linked account then i will try link my twitch now
ive put a new email on my twitch

**Comment by marcandrews** [comment]
Please send an email to `support@overlay.expert` from the email you use for your Twitch account and I will delete the linked account.

**Comment by yellowsthegoat** [comment]
Sorry, ***@***.*** is the email now linked to my twitch

Kind regards

**Comment by marcandrews** [comment]
Please sign out of Overlay Expert and then sign back in with Twitch. This will update our records, I can confirm that you are the account holder, and then I can remove the account.

**Comment by yellowsthegoat** [comment]
Done, signed in with my twitch..

**Comment by marcandrews** [comment]
Please continue via email.

**Comment by yellowsthegoat** [comment]
So which account will get deleted? The overlay expert account that i signed
up with facebook?

**Comment by yellowsthegoat** [comment]
Done
