### ISSUE TITLE
Can't activate overlay

### ISSUE THREAD

**Issue by zarcad** [overlay-expert/help-desk#332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Twitch username

zarcad1

### Expected Behavior

should activate

### Current Behavior

When I go to activate the Overlay Expert extension on the Twitch site, after I click "Activate" and "Set as Overlay 1", I get a gray popup box that displays a spinning circle icon. It just keeps spinning and the extension is never activated.

### Steps To Reproduce

1. Go to Extensions on Twitch
2. Click on My Extensions
3. For Overlay Expert, click on Activate, then on Set as Overlay 1

### I am streaming from

Console

### I am viewing from

PC/macOS/Linux web browser

### Are you using the Twitch Extension?

Yes

### Web browser

Firefox

**Comment by zarcad** [comment]
Never mind.  I fixed it by using Microsoft Edge instead of Firefox.

**Comment by marcandrews** [comment]
This issue duplicates https://github.com/overlay-expert/help-desk/issues/330#issuecomment-1116126279. Please search before creating a new issue.
