### ISSUE TITLE
No option to select saved overlay in twitch extension

### ISSUE THREAD

**Issue by Dracogeezy** [overlay-expert/help-desk#336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Twitch username

DracoGeezy

### Expected Behavior

Should give me a "choose" option when i click to configure extension on twitch and there is nothing there. Just purchased a $25 overlay and cannot use it. 

### Current Behavior

No option to "choose" my overlay on twitch extension. Irritated. Been messing with it for HOURS.

### Steps To Reproduce

customize overlay
save overlay
go to twitch
install overlay expert
link accounts
click my extensions
configure
no option to choose overlay
back to step 1
absolutely irritating

### I am streaming from

Console

### I am viewing from

PC/macOS/Linux web browser

### Are you using the Twitch Extension?

Yes

### Web browser

Other

### Anything else?

Just wish it would work so my stream doesn't look bland...again

**Comment by marcandrews** [comment]
Is this the same as https://github.com/overlay-expert/help-desk/issues/199?

What browser are you using? Your browser's security setting may be too strict for Twitch Extensions. Can you try lowering them?

**Comment by Dracogeezy** [comment]
Was literally working a couple days ago and now nothing. I haven't changed a single thing. And now I have completely turned off all security settings period and still the same result. My other extensions are working on Twitch. I have also already tried the "set to extension" selection directly from overlay expert and still no luck....

**Comment by Dracogeezy** [comment]
Also, my browser is microsoft edge.... but like i said, it was just working a couple of days ago. and no, it is not the same as #199. my screen wont even show to choose from marketplace.

**Comment by marcandrews** [comment]
Can you upload a screenshot?

**Comment by Dracogeezy** [comment]
![Web capture_14-6-2022_82614_overlay expert](https://user-images.githubusercontent.com/103005448/173576732-fd27773c-3ec5-4cab-9d95-03867c9e8457.jpeg)

![Web capture_14-6-2022_82545_dashboard twitch tv](https://user-images.githubusercontent.com/103005448/173576780-c881827c-a988-4dab-acc6-2e721fb18aa1.jpeg)

**Comment by marcandrews** [comment]
This looks like https://github.com/overlay-expert/help-desk/issues/26. Is the time/timezone correct on your PC?

**Comment by Dracogeezy** [comment]
You are a genius and stress reliever!! Problem solved. Thank you so much! I wonder what caused my laptop to change to Pacific Time and I am Eastern. Seriously have not changed anything on here! Thank you again.
