### ISSUE TITLE
Overlay Expert Twitch Extension won't show my custom overlay or templates

### ISSUE THREAD

**Issue by devithius** [overlay-expert/help-desk#337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Twitch username

devithius

### Expected Behavior

Open to configure extension

Templates load in then my created overlays load in underneath.

### Current Behavior

I cannot currently select any overlays within the extension.

### Steps To Reproduce

1. Creator Dashboard
2. Extensions
3. Configure Overlay Expert

### I am streaming from

Console

### I am viewing from

PC/macOS/Linux web browser

### Are you using the Twitch Extension?

Yes

### Web browser

Chrome

**Comment by marcandrews** [comment]
This issue duplicates https://github.com/overlay-expert/help-desk/issues/26. For the solution, please see https://github.com/overlay-expert/help-desk/issues/26#issuecomment-642380393.
