### ISSUE TITLE
Unable to activate overlay expert

### ISSUE THREAD

**Issue by h4ppyc4tl4dy** [overlay-expert/help-desk#338]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Twitch username

happy_cat_lady 

### Expected Behavior

Click on activate to have overlay expert move from installed to activated.

### Current Behavior

Click on activate, a blank window pops up with a swirling circle in the middle, an X in the top right corner and nothing. I have logged out and back in, uninstall and reinstalled and refreshed browser

### Steps To Reproduce

1. Go to my extensions
2. Click on activate 
3. Set as overlay 1
4. Blank window pops up - unable to continue

### I am streaming from

Console

### I am viewing from

Other

### Are you using the Twitch Extension?

Yes

### Web browser

Chrome

### Anything else?

![Screenshot_20220712-161354_Samsung Internet](https://user-images.githubusercontent.com/109161538/178524484-3d320720-1f50-4b26-8bac-60109119c3a3.jpg)

**Comment by marcandrews** [comment]
That browser is not Chrome; please try Chrome.

**Comment by h4ppyc4tl4dy** [comment]
Set Chrome as default browser, but still nothing 
![Screenshot_20220729-191454_Chrome](https://user-images.githubusercontent.com/109161538/181820316-6f3bb26b-d481-4be6-b5fa-b3636cf728a6.jpg)

**Comment by h4ppyc4tl4dy** [comment]
Just thought I'd let you know that when I tried to activate my extension, I got a confirmation and the program has moved from the left to the right of the screen underneath "activated". I'll be streaming soon(ish), so I'll check it out to see if its worked 🤞

**Comment by marcandrews** [comment]
Awesome!!!
