### ISSUE TITLE
Twitch Extension Keeps Loading

### ISSUE THREAD

**Issue by JakeBrozLow** [overlay-expert/help-desk#340]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Twitch username

JakeBrozLow

### Expected Behavior

1. Activate Overlay
2. Add to overlay 1
3. Done

### Current Behavior

When going to push Activate Extension it just keeps loading

### Steps To Reproduce

1. Activate Overlay
2. Add to overlay 1
3. Done

### I am streaming from

Console

### I am viewing from

iOS web browser

### Are you using the Twitch Extension?

Yes

### Web browser

Safari

**Comment by marcandrews** [comment]
This is a known bug with Twitch and browsers other than Chrome. Please try again with Chrome.

**Comment by YoAcrosel** [comment]
im still having this issue and ive tried chrome and safari
