### ISSUE TITLE
overlay.

### ISSUE THREAD

**Issue by testiiii** [overlay-expert/help-desk#341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Twitch username

jealousy_bat

### Expected Behavior

nothing bad works great im now on pc using a capture card and want to use this overlay i purchaed for 19.99 pixie animated on my streamlabs.

### Current Behavior

nothing bad works great im now on pc using a capture card and want to use this overlay i purchaed for 19.99 pixie animated on my streamlabs. 

### Steps To Reproduce

nothing bad works great im now on pc using a capture card and want to use this overlay i purchaed for 19.99 pixie animated on my streamlabs.

### I am streaming from

Console

### I am viewing from

PC/macOS/Linux web browser

### Are you using the Twitch Extension?

Yes

### Web browser

Chrome

### Anything else?

nothing bad works great im now on pc using a capture card and want to use this overlay i purchaed for 19.99 pixie animated on my streamlabs.

**Comment by marcandrews** [comment]
Thanks for your feedback 💜 

Unfortunately, overlays purchased on Overlay Expert are meant to be used with Overlay Expert. To use them with another service, you will need to manually transfer it.
