### ISSUE TITLE
StreamElements Event-based Alert for Donation & Tips

### ISSUE THREAD

**Issue by WM854-7** [overlay-expert/help-desk#342]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Twitch username

WM854_7

### Please Describe The Problem To Be Solved

Hello how are you? i have a small suggestion as I use StreamElements for donations & Tips and i was wondering/hoping if it would be possible for a new Event-based Alert for Donations or Tips as i don't use Stripe for Streaming i understand if this feature is not possible but it's worth asking.

### Suggest A Solution

A new Event-based Alert called Donations or a Event-based Alert called Tips if possible please so it's basically like the follower alert but instead it tells you who donated & how much they donated or tip you for StreamElements.

### Anything else?

No that's it :)

**Comment by marcandrews** [comment]
StreamElements (and StreamLabs) need to allow Overlay Expert to integrate with them, so unfortunately there is nothing we can do on our side. What you can do, however, is to contact StreamElements and StreamLabs and ask them to add support for Overlay Expert.

In the meantime, you can use [Overlay Expert Celebrations](https://overlay.expert/celebrations) for tips/donations. Signing up for Stripe is easy and only takes a few minutes.
