### ISSUE TITLE
Chatbox Pronouns Extention

### ISSUE THREAD

**Issue by Wuffli** [overlay-expert/help-desk#345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Twitch username

Wuffli

### Please Describe The Problem To Be Solved

Currently the Pronouns Twitch-Chat extension [Twitch Chat Pronouns](https://pronouns.alejo.io/) is only, according to my research, available on twitch itself. I would love to be able to display these pronouns in my Stream in the Chat-box too.

### Suggest A Solution

I dont exactly know how this would work but i know that this extension has an api maybe this helps?

**Comment by marcandrews** [comment]
Thanks for your feedback. Unfortunately there is nothing we can do on our side. You will have to reach out to developers of Twitch Chat Pronouns and ask them to add support for Overlay Expert.
