### ISSUE TITLE
custom background pics not working for overlay

### ISSUE THREAD

**Issue by etown209** [overlay-expert/help-desk#346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Twitch username

etown209

### Expected Behavior

trying you add a custom picture to a layer for a solid bar across the top, custom pictures for alerts. 

### Current Behavior

after I up load the picture it uploads and I can select the picture. I save and exit and in the preview it shows the custom picture but when I go live its not showing it. ill go back and take the custom picture out and select a solid color and the save, go live and it shows the solid color. 

### Steps To Reproduce

1. open overlay
2. load overlay
3. select the layer
4. upload then select the custom picture
5. top left check mark, clicked
6. clicked the cloud to save
7.saved

### I am streaming from

Console

### I am viewing from

PC/macOS/Linux web browser

### Are you using the Twitch Extension?

Yes

### Web browser

Safari

**Comment by etown209** [comment]
this has been 8 days and nothing has change  anyone!??

**Comment by marcandrews** [comment]
Sorry for the belated reply and that you are having issues.

Is the background image in WebM format?

**Comment by etown209** [comment]
Hello. Thanks for the response 

So uploading doesn’t seem like it’s the problem cu I see the image to click from but after I click it , it doesn’t show up on the screen. Or in preview.  Custom pic for alerts or adding a custom pic to make boarders. If I choose a color for those spots it shows up. Now if I upload the custom pics then save it. Go back into the program and I can choose the lay out. It shows the custom photo.

**Comment by marcandrews** [comment]
What is the format of the image? Can you upload the image that does not work here?

**Comment by etown209** [comment]
I provide the exact info. The futon background I put is not working.

**Comment by PristineFrog530** [comment]
> I provide the exact info. The futon background I put is not working.

They asked you for the image format and an upload of the image so they can work on figuring it out. It went stale because you never followed back up with the needed information. Not all images are created equal and sounds like some things will not load if in a certain format.

**Comment by etown209** [comment]
![woodland](https://user-images.githubusercontent.com/111474623/189569112-427ca202-e24a-4ace-a688-7b95a6463649.png)
 this is the image

**Comment by etown209** [comment]
![depositphotos_160491542-stock-illustration-topographic-map-pattern](https://user-images.githubusercontent.com/111474623/189569177-d4df9d80-a325-4294-bffa-711d6d9a2bb7.jpeg)
