### ISSUE TITLE
Overlay that shows Twitch chat messages

### ISSUE THREAD

**Issue by rcktman0127** [overlay-expert/help-desk#355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Twitch username

rcktman0127

### Please Describe The Problem To Be Solved

I believe it would be a great idea for there to be an overlay that shows Twitch chat messages without requiring a command. As far as I can tell, the only way to have any messages appear on the overlay is to have a command input connected to the message.

### Suggest A Solution

It would be useful to have an overlay layer similar to the one that is activated by a Twitch command in chat, but have the overlay have the ability to show chat without the required use for a command. It seems to look more professional for a streamer to show the chat messages on stream.

### Anything else?

I can't think of anything, if there is a way to add this overlay already, I would greatly appreciate an explanation on how to do it. I have already checked through the list of suggestions and haven't found any issues that are the same as the one I present.

**Comment by marcandrews** [comment]
You mean something like the Twitch Chat Widget https://twitter.com/OverlayExpert/status/1262617329059475462?
