### ISSUE TITLE
Cant sign into overlay expert

### ISSUE THREAD

**Issue by GaloreJ** [overlay-expert/help-desk#356]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Twitch username

GaloreJ

### Expected Behavior

I expect to be able to log in and change or edit my overlays.

### Current Behavior

I hit the sign in then hit twitch and it goes to a black screen and says 

{"status":500,"message":"internal server error"}

### Steps To Reproduce

clicked configure overlay

clicked on overlay of choice to edit

tried to hit the sign in for overlay

then hit twitch

then gave me the black screen with the following message

{"status":500,"message":"internal server error"}

### I am streaming from

Console

### I am viewing from

Twitch Mobile App

### Are you using the Twitch Extension?

Yes

### Web browser

Chrome

### Anything else?

please email beehartman95@gmail.com with the solution to this issue. 

Thanks

**Comment by marcandrews** [comment]
Unfortunately, this is an issue with Twitch. 

If you used the same email for Twitter, Facebook or Google, you can use that method to sign in instead; otherwise we must wait for Twitch to resolve the issue.

**Comment by GaloreJ** [comment]
So do I need to report the issue with twitch then?

**Comment by marcandrews** [comment]
You can, but they are already aware of the issue and are working on resolving it.

**Comment by GaloreJ** [comment]
Awesome thank you.
