### ISSUE TITLE
Dynamic Handle - Money or Donation Platform

### ISSUE THREAD

**Issue by JackJallo** [overlay-expert/help-desk#48]
**Is your feature request related to a problem? Please describe.**
The idea is to link a viewer to a streamer's money platform. Considering the multitude of how many of these there are, I'd focus on doing them one at a time, if this was to be a thing. PayPal makes the most sense to start with, I believe. There is also platforms like Venmo, CashApp, Google Pay, Zelle, and even Patreon. I can, like with the other Dynamic Handle feature requests, make separate posts for each of these, too, if that helps.

**Describe the solution you'd like**
Same concept as the Instagram, Google, or Steam Dynamic Handles that I think would work similarly.

**Screenshots**
N/A

**Describe alternatives you've considered**
There are other Handles that I believe should be added.

**Additional context**
Nothing else to really add!

**Comment by marcandrews** [comment]
For now, only tips via Overlay Expert Celebrations are supported, so other donation platform handles will not be added in the near future.
