### ISSUE TITLE
Option to quickly move a layer to the top or bottom of the layer section

### ISSUE THREAD

**Issue by JackJallo** [overlay-expert/help-desk#49]
**Is your feature request related to a problem? Please describe.**
The problem is that it can sometimes be a pain to click and drag layers around when there could be an option to add a button or buttons to the 3 vertical dot drop-down menu that can automatically throw the layer to the top of the section or to the bottom. The pull/drag way that it works now can be a little clunky. I find myself having to move a layer above 4 layers, then scroll up, and repeat, and so on until it gets to the top or bottom where it may not even need to sit, but may be used as a helpful, and quick way get a layer to the bottom and then can be dragged above 2 layers from the bottom, for example, rather than dragged and then scroll and then dragged and then scroll, etc.

**Describe the solution you'd like**
The solution I'm looking for is pretty much stated above as it is so directly tied to the describing the problem. In short, the solution would be to add a button or buttons to auto move a layer to the top or bottom of the layer section.

**Screenshots**
N/A

**Describe alternatives you've considered**
If the above can't be done, then maybe allow the Overlay Settings panel to be autoscrollable (?) as you drag a layer upwards, it would push the section upwards, and vice versa. Truthfully, both options sound good to add for more fluidity.

**Additional context**
Nothing to really add on top of all of this!

**Comment by marcandrews** [comment]
You can now reorder layers from the layer list.

<img width="1216" alt="Screen Shot 2020-08-02 at 1 26 42 PM" src="https://user-images.githubusercontent.com/3518829/89128568-8d72a200-d4c4-11ea-9dbc-5cb81962e0fe.png">
