### ISSUE TITLE
Browser Tab Overlay Integration 

### ISSUE THREAD

**Issue by JackJallo** [overlay-expert/help-desk#51]
**Is your feature request related to a problem? Please describe.**
The idea is that having the same "Builder - Overlay Expert" browser tab is fine on its own, but if you have multiple open, it can be frustrating to move throughout different overlays, especially when you're trying to match certain placements or ideas from one overlay to another. It would alleviate the issue to an extent by simply having a more visually organized tab section that could save both time and frustration due to not realizing you maybe editing the wrong overlay.

**Describe the solution you'd like**
If there is a way to populate the title of the overlay within the browser tab section to where it might look like "SoT - Builder - Overlay Expert" instead of just "Builder - Overlay Expert" that would be grand. When moving through overlays to figure out which is which, I could save so much time by just have the title appear on the tab itself. Plus, it's a glance to look up and then back at what you're doing, rather than having to stop what you're doing so that you can scroll up to the top of the Overlay Settings panel to make sure you're in the right place. 

**Screenshots**
I could take a screenshot and edit it to make it look more along the lines of what I see. One way to reproduce this for yourself would be to have the OE Help Desk tab up as well as the Builder - OE tab up and see that the font sizes and what not do not match, and so adding something like this I don't believe is impossible when it comes to tab-lettering-formatting-things?

**Describe alternatives you've considered**
An alternative would be to have "Builder" customized from the overlay itself with a section near title, game, etc. that has a max amount of characters or something so that instead of "Builder - Overlay Expert", it could instead say "SoT - Overlay Expert" or maybe even "Sea of Thieves - Overlay Expert" if the number of characters arent too restricted. 

**Additional context**
Maybe I'm the only one with this problem, but ease of use is such an important piece of any sort of program, tool, or project that can make new people feel like they have better control of what they're doing, as well as reducing the risk of having someone, for example, change up an entire overlay and save it, but only to find out that it was for the wrong game. It won't fix everything, and I dont even know if it's possible. Maybe some sort of OE API direct link to the browser could help? I'm not very tech saavy, esp when it comes to software I don't quite understand. 

As someone who tends to work on multiple layers at once, I know that the idea of "Cool! New game to Stream!" can, when in a maybe not so great or productive mood, cause a sort of a drag to that initial good feeling, realizing that you have to make another overlay to fit the game, but more so compounded with the fear or cautiousness that slows the process down because outside of a couple of ways to affirm you're in the right tab, it could actually be (in theory) a much more accessible way for people to handle their overlays and changes with one, two, three, or whatever amount of things less to worry about.

**Comment by marcandrews** [comment]
I added the overlay title and save state to the browser titlebar.

<img width="640" alt="Screen Shot 2020-07-26 at 1 54 41 PM" src="https://user-images.githubusercontent.com/3518829/88486796-488fbe00-cf4e-11ea-8b12-fa30da15164d.png">
