### ISSUE TITLE
Delete Overlay Option - Lack of Confirmation

### ISSUE THREAD

**Issue by JackJallo** [overlay-expert/help-desk#55]
**Is your feature request related to a problem? Please describe.**
I haven't run into this problem yet, but if I did, I'd be really upset. The feature added would be akin to an "Are you sure? Yes or No?" sort of deal when you go to delete an overlay, or maybe go to clone one only to accidentally click delete.

**Describe the solution you'd like**
Basically just that. Add an extra confirmation like a Yes or No, or if you press delete with your mouse, etc. you'll then have to type out "delete" so that it can't be done by accident.

**Screenshots**
N/A

**Describe alternatives you've considered**
An alternative, honestly, would be to have the feature removed and tucked away somewhere like in a corner of the page. You'd select the trash button and then select the overlay, but even then, a confirmation should still be necessary. If not add a confirmation upon deletion, maybe have a "trash bin" that allows you to restore contents/empty contents? It automatically empties after 14 days or something. Those are the only alternatives I can think of.

**Additional context**
N/A

**Comment by marcandrews** [comment]
Confirmations offer a suboptimal user experience, but you can now undo delete.
