### ISSUE TITLE
Webcam Integration

### ISSUE THREAD

**Issue by HAMBON3malon3** [overlay-expert/help-desk#57]
Hello!

I am trying to get my webcan (usb) from my console to be plugged into my stream, but when I use it directly from the console It destroys my audio.  I have been trying to troubleshoot this for a while but cannot get it to work for me!

**Describe the solution you'd like**
I would love to have a feature to add a webcam from the computer as a layer on the overlay extension.  It would make the resizing really beneficial, as well as being able to get a solid personal touch to the people in the stream.  I am unsure of how to do this!

**Describe alternatives you've considered**
I have not looked into any alternatives yet as I have been trying to mainly troubleshoot the layers as well as any issues that may be with the camera itself.  I am using an XBOX ONE to stream.  The fact I dont have to use an outside source is amazing and I would love to have it hit all in one!

**Additional context**
Nothing additionally other than the fact that I love the overlay maker and was truly able to customize it to my exact desire!  Its amazing!

**Comment by marcandrews** [comment]
This is a great idea, but to implement it is equivalent to creating our own streaming platform, which is complicated and expensive.
