### ISSUE TITLE
[Dynamic Button] **Latest Cheer Display Name**

### ISSUE THREAD

**Issue by JackJallo** [overlay-expert/help-desk#58]
**Describe the bug**
My "Latest Cheer" Panel, which consists of a black background and a nested layer with another background + 2 separate lines of text groups, does not update the second line which consists solely of the "Latest Cheer Display Name" with the newest cheerer. It, instead, stays **stuck** on someone who sent me bits a week or two before the last bit influxes. 

**To Reproduce**
1. Make a layer for "latest cheerer"
2. Add a line of plain text in the text groups portion of the Content section
3. Add another line in the text group (#2) but instead only add the "Latest Cheer Display Name" dynamic button
4. Place wherever, and save

**Expected behavior**
It should be displaying the latest person's Twitch name who has sent in Bits instead of being stuck on someone who sent in Bits whenever before this latest person.

**Twitch channel**
https://twitch.tv/JackJallo1

**Screenshots**
![Screenshot (84)_LI](https://user-images.githubusercontent.com/27311142/87670501-d1804b80-c73d-11ea-8e03-4050ea2b771e.jpg)
![Screenshot (85)_LI](https://user-images.githubusercontent.com/27311142/87670503-d2b17880-c73d-11ea-868c-0acb63d1f3a4.jpg)
![Screenshot (86)_LI](https://user-images.githubusercontent.com/27311142/87670504-d2b17880-c73d-11ea-8375-957e57b29e7e.jpg)
![Screenshot (87)_LI](https://user-images.githubusercontent.com/27311142/87670506-d34a0f00-c73d-11ea-836c-658f89f43f7f.jpg)
![Screenshot (88)_LI](https://user-images.githubusercontent.com/27311142/87670508-d34a0f00-c73d-11ea-9247-edb1d3a1d366.jpg)
![Screenshot (89)_LI](https://user-images.githubusercontent.com/27311142/87670509-d3e2a580-c73d-11ea-99d1-792a395f3b6a.jpg)
![Screenshot (90)_LI](https://user-images.githubusercontent.com/27311142/87670511-d47b3c00-c73d-11ea-8da7-2901306e0a0c.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 (64-Bit [I believe])
 - Browser: Chrome
 - Version: I believe everything is as updated as can be.

**Smartphone (please complete the following information):**
N/A

**Additional context**
This has been going on for about 4, maybe 5 days. I kept thinking it would fix itself, or that I'd just find a workaround or something, but I saw someone else complain about the same issue so it became a priority to bring this up.

**Comment by marcandrews** [comment]
1. What happens when you try the test cheer chat command `!test twitchCheer`?
2. Was the overlay running (i.e. were you live) when you received the cheer from literal1?

**Comment by JackJallo** [comment]
1. Nothing happens. I haven't tried the test online, but the !test commands usually work offline for me.

2. It was running, I was live when I got the cheer from literal1, but I also was live when the newer Bit donations came in as well. I don't remember if the Alert went off, but I do remember getting them while live and talking to my friend about it mid-stream.

**Comment by marcandrews** [comment]
Can you try signing out and signing back into Overlay Expert?

**Comment by JackJallo** [comment]
I tried that and it didnt seem to work, but after doing the cache fix + this, it now updates accordingly. Thank you! Sorry for getting back to this so late.

**Comment by marcandrews** [comment]
No worries. Thanks for the update.
