### ISSUE TITLE
no one can see my overlay other than me

### ISSUE THREAD

**Issue by thatstonedarrow** [overlay-expert/help-desk#62]
**Describe the bug**
no one can see my overlay no matter what platform they are on. it shows that overlay expert is on and active just not showing it. ive uninstalled and reinstalled. ive changed overlays. ive tried every device. i can see in my stream manager that its on the stream just others cant see it. 

**To Reproduce**
1. Go to my stream on anything and see. 

**Expected behavior**
i expected people to see my overlay

**Twitch channel**
https://twitch.tv/thatstonedarrow

**Screenshots**
i cant give you screen shots other people would have to send them to me.

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: firefox opera chrome
 - Version all up to date
![Screenshot (1)](https://user-images.githubusercontent.com/68489273/87866266-25a94c80-c945-11ea-8e83-c80d5e672b17.png)

**Smartphone (please complete the following information):**
 - Device: all
 - OS: android and ios
 - Browser all of them
 - Version up todate version

**Additional context**
ive given as much info as i can i cant sit her for 3 days listing all 40 smart phones and 30 different computers.

**Comment by marcandrews** [comment]
When next will you be live?

**Comment by thatstonedarrow** [comment]
I don't normally have a set time but I'm normally live after 10pm central us. If you need me to stream another time I can make it work.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by marcandrews** [comment]
I can see your overlay just fine.

![Screen Shot 2020-07-19 at 11 32 29 PM](https://user-images.githubusercontent.com/3518829/87897064-32e33b80-ca18-11ea-94d5-209419237315.png)

There is no difference between your view and your viewer's view, so if you can see your overlay, that means your viewers can see it too.

If your viewers are reporting that they cannot see your overlay, it usually means they are watching from mobile or other device that does not support Twitch extensions. For more information on Twitch extension support on devices other than desktop, please see [here](https://github.com/overlay-expert/help-desk/blob/master/twitch-extension.md#why-doesnt-my-overlay-show-on-mobile-or-other-platform).

**Comment by mpek** [comment]
Did you try to see his overlay on Android or iOS? Mine does not show on Android
