### ISSUE TITLE
it wont let me save my overlay and it said to come here if it kept happening.

### ISSUE THREAD

**Issue by blizzardgamer0** [overlay-expert/help-desk#65]
![Screenshot 2020-07-23 at 14 05 24](https://user-images.githubusercontent.com/68695437/88289770-a70a3180-cced-11ea-924e-3fb85b3cc3b7.png)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Twitch channel**
https://twitch.tv/username

**Screenshots**
[e.g. Builder, Extension Configuration Screen, etc.]

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by marcandrews** [comment]
This is should be resolved. Let me know if you still have trouble saving your overlay.

**Comment by jauminho** [comment]
Hello! I have a similar problem. May I ask how it was resolved?
