### ISSUE TITLE
Twitch. Expert overlay issue.

### ISSUE THREAD

**Issue by ToverTealeaf** [overlay-expert/help-desk#68]
So im new to all this stuff really. When i'm adding my alerts in I have them set to come on only when the event happens, like getting a new follower. I have a little gif and a text that should show up, but i'm not getting any of that. The rest of overlay works well, but this feature will truly help me out. 
Any ideas or help would be very helpful, Thanks.

The images i've attached are what it should be. I see it working on the builder part but not on the stream.

![Annotation 2020-08-07 112746](https://user-images.githubusercontent.com/69357838/89662545-414ba700-d8a2-11ea-8773-2b7ace67dc35.png)
![Annotation 2020-08-07 113707](https://user-images.githubusercontent.com/69357838/89662615-59bbc180-d8a2-11ea-8882-248ee69da844.png)

**Comment by marcandrews** [comment]
1. Please show all the alert settings for your layer.
2. Did you follow and try the test commands in [this help article](https://github.com/overlay-expert/help-desk/blob/master/builder.md#alerts-and-how-to-add-them-to-your-overlay)?

**Comment by ToverTealeaf** [comment]
![image](https://user-images.githubusercontent.com/69357838/89696317-5695f500-d8e5-11ea-846f-33bdb67d5c67.png)
i went through the test commands from the article and that helps alot

**Comment by marcandrews** [comment]
800 ms is **0.8 seconds**. Only Shroud would see this alert 😅 

Try setting the Show to 5000-10000 ms (or 5-10 seconds). Also, you should set Slow-mode to 0 ms. Re-follows within the same stream are ignored to prevent abuse. This is all in the [help article](https://github.com/overlay-expert/help-desk/blob/master/builder.md#alerts-and-how-to-add-them-to-your-overlay); please read it carefully.

**Comment by ToverTealeaf** [comment]
thanks i will
