### ISSUE TITLE
Does not show overlay at all

### ISSUE THREAD

**Issue by xsiegerage** [overlay-expert/help-desk#72]
i made my own overlay for my twitch stream and

**Describe the bug**
when i started streaming i didn't see it and nobody else could either. (Overlay wasn’t showing)

**To Reproduce**
1. Go to your twitch extensions
2. Click on activate and add layer, select witch one you want
3. Start Stream on console

**Expected behavior**
I expected it to show my overlay to everyone in my stream.
**Twitch channel**
https://twitch.tv/xsiegerage

**Screenshots**
Extension Configuration Screen

**Desktop (please complete the following information):**
 - OS: 
 - Browser 
 - Version 

**Smartphone (please complete the following information):**
 - Device: iphone 11
 - OS: IOS 13.6.1
 - Browser: safari

**Additional context**
I set everything up and activated and added to my stream, i started streaming on my xbox one s and i didn't see it on my phone.(i was watching chat and my stream playback on my phone) it said the extension was activated and on on my phone but i didn't see it.

**Comment by marcandrews** [comment]
Please read the [FAQ](https://github.com/overlay-expert/help-desk/blob/master/twitch-extension.md#why-doesnt-my-overlay-show-on-mobile-or-other-platform).
