### ISSUE TITLE
My viewers CANT see my overlay

### ISSUE THREAD

**Issue by Mrtrollxblv4** [overlay-expert/help-desk#77]
**Describe the bug**

my viewers cant see my new overlay

**Expected behavior**
I was waiting to all the people that entered my stream would be able to see the overlay i choosed but none can

**Twitch channel**
https://twitch.tv/mrtrollxbl_v4

+

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]
 - Version [22]

**Comment by tristan210** [comment]
Same
