### ISSUE TITLE
Animated Overlays

### ISSUE THREAD

**Issue by DeadlySilentSHH** [overlay-expert/help-desk#81]
You should add the option to use custom animated overlays such as camera outlines and other stuff like that. I have been trying for hours to get my animated overlay up and its not working. It only lets me pick images and not videos.

**Comment by marcandrews** [comment]
See [What image and sound files sizes, types and formats are supported?](https://github.com/overlay-expert/help-desk/blob/master/builder.md#what-image-and-sound-files-sizes-types-and-formats-are-supported).
