### ISSUE TITLE
Variables usage for Chat events

### ISSUE THREAD

**Issue by LautaroAp** [overlay-expert/help-desk#87]
**Descriotion**

I need to manage alerts through the interaction of the chat and the channel points or commands.
On twitch, when a viewer redeems channel points, it is shown as follows:

- **{user}** has exchanged **{item}** **{icon}** **{points}**
- Example: **Kuroitenshi** has exchanged **Goblin** 💎 **1**

I need to catch this text sent by twitch (not by users) and identify the **{item}**, discarding the excess text and trigger an alert

**Screenshots**

![image](https://user-images.githubusercontent.com/43177027/94595617-77355800-0261-11eb-8b33-32982583c97c.png)

**Comment by marcandrews** [comment]
Even though channel point redemption events _appear_ in your chat, they are not yet part of the Chat API, and therefore, not available to Overlay Expert or any chat bot.

For this functionality, we will need to wait until Twitch add channel point events to the [Chat API](https://dev.twitch.tv/docs/irc/tags#usernotice-twitch-tags) unfortunately.

**Comment by LautaroAp** [comment]
Hi! Thanks for the reply!

And is there a way to take a part of the string? That is, if I have "aa bb cc", check if it contains "bb"

**Comment by marcandrews** [comment]
The pattern field accepts [regular expression](https://regexr.com). If you give me a better example of the message you wish to match, I can help you with the regular expression required to match the message.

**Comment by LautaroAp** [comment]
Thanks! I tried something simple using any entry /.*/ , but it does not take the messages generated by Twitch, only those of users (last one)

![image](https://user-images.githubusercontent.com/43177027/94671092-caeb8400-02e9-11eb-9737-66c52c6c181d.png)

Another alternative is to force a message to be entered when redeeming channel points, but it can be activated by normal chat (activate by !goblin )

![image](https://user-images.githubusercontent.com/43177027/94671511-5cf38c80-02ea-11eb-94c1-b9d7e0ea77bd.png)

It seems that at the moment there is no solution, this would be an excellent interaction feature.
