### ISSUE TITLE
How do you make your alerts show for longer/shorter times? 

### ISSUE THREAD

**Issue by SweatyPalmsFPS** [overlay-expert/help-desk#89]
How do you adjust the amount of time an alert is shown on screen? For example, I have a "New Follower" Alert that I can not get to stay on screen more than about a second or 2..

I'm new to using this and I'm sure I'm probably overlooking it somewhere..someone please help me!

**Comment by marcandrews** [comment]
Under Alerts, increase the Show value, which is in milliseconds (1000 milliseconds = 1 second).
