### ISSUE TITLE
Alerts and how to add them to your overlay

### ISSUE THREAD

**Issue by marcandrews** [overlay-expert/help-desk#91]
From the Builder, create a new layer, and then under _Layer Settings_, expand the _Alerts section_. Once there, change the Type to **Event-based** and then configure your alert.

The _Show time_ is the amount of time in milliseconds the alert will show. Start with a _Show time_ of `5000`-`10000` ms (or 5-10 seconds).

The _Slow-mode_ time will cause alerts that follow a previous alert within this time period to be ignored. Set this to `0` ms.

To add the text to your layer specific to the event, such as the follower's name or resubscribe months, expand the _Content section_ and under _Layer Text Groups_, click on _Add new a new text group_ or _edit an existing text group_. Under _Text Group Setting_ and the _Alert_ category, dynamic items specific to the alert event you have configured will be available to choose.

#### Test commands

Once your alerts are configured, you may test them in the Builder and while streaming by typing the following (case-sensitive) into your chat as a broadcaster:

- `!test twitchFollow`
- `!test twitchSubscribe`
- `!test twitchResubscribe`
- `!test twitchGiftedSubscribe`
- `!test twitchCheer`
- `!test twitchHost`
- `!test twitchRaid`
- `!test twitchRitual`

#### Alert delays

All alerts are instantaneous with the exception of follow alerts, which may take up to 30 seconds to show. To prevent abuse, re-follows within the same stream are ignored.

**Comment by SoyBoyIII** [comment]
To see followers names in the streams, do i keep the "New content Item" and twitch follow, or do I remove the "new content item" and just keep the twitch follow alert.

**Comment by jam5quad** [comment]
Buenas noches, quisiera saber como poner en las alertas la opción de cuando otro usuario de twitch te esta Hosteando ya que no me aparece esa opción, o bien saber si ya no esta disponible esa parte. Agradezco su atención.

**Comment by marcandrews** [comment]
@jam5quad Official support is only provided in English, but you might be able to get help from the community in Spanish on our [Discord](https://overlay.expert/r/discord).

**Comment by johan718** [comment]
For some reason, when I set my overlay panel to trigger on a Twitch Chat event, nothing happens during chat. If I set the panel to always on, everything works fine. I'm on PS4.

**Comment by Bongo-0** [comment]
![image](https://user-images.githubusercontent.com/92965980/138390321-50dd1afc-1446-4d1f-9b6a-204ab536090f.png)
i dont understand where to get or what the link does?
